chipsalliance/sv-tests

- README.md
- runners/icarus
- runners/verilator
This adds runners that can be used to check if Icarus and Verilator are able to parse the test files
> Add simple runners for Icarus and Verilator

- tests/sanity.sv
> tests: fix the sanity-check test tags

- README.md
> Make project names links in the README

- Makefile
- tools/runner
Also add some extra sanity check that the bash code did not have.
> tools: rewrite the runner wrapper in python

- conf/lrm.conf
Contains all the chapters (and their subchapters) we intend to test.
Generated with mutool:
mutool show <pdf_file> outline > <lrm_file>
And some commands in vim:
:%s/^[^"]*"//g
:%s/"[^"]*$//g
:%s/^\([0-9.]\+\)\.\? /\1\t/g
:%s/\.\t/\t/g
The interesting chapters (5-9, 11, 12) were then copied by hand.
> database: generate a new input database

- .gitmodules
- Makefile
- README.md
- tools/runner
- tools/runners.mk
- tools/sv-report
This PR:
* Adds all the tested tools as submodules (to be updated by a bot)
* Adds makefile targets to build all the tools (all of them are pretty different so there is a new target for all of them)
* Builds all the tools before generating the report
Closes #37 
This is also needed for: #36 #33
> Add all tested tools to the system

- .gitmodules
- .travis.yml
- Makefile
- README.md
- conf/requirements.txt
- tools/runners.mk
A kind of race condition happend and the CI fails on current master. This PR should find and fix those issues.
> CI Fixes after adding tools building

- .travis.yml
Uses variables from #36 
Closes #36
Depends on #41 
> ci: deploy report using github pages

- .travis.yml
CI stopped working correctly after adding report deployment to github pages, this PR aims to fix that
> ci: fix gh pages deployment

- generators/uniquecase
- tests/chapter-12/12.4--if.sv
- tests/chapter-12/12.4--if_else.sv
- tests/chapter-12/12.4.1--if_else_if.sv
- tests/chapter-12/12.4.2--priority_if.sv
- tests/chapter-12/12.4.2--unique0_if.sv
- tests/chapter-12/12.4.2--unique_if.sv
- tests/chapter-12/12.5--case.sv
- tests/chapter-12/12.5.1--casex.sv
- tests/chapter-12/12.5.1--casez.sv
- tests/chapter-12/12.5.2--case_const.sv
- tests/chapter-12/12.5.4--case_set.sv
- tests/chapter-12/12.6.1--case_pattern.sv
- tests/chapter-12/12.6.1--casex_pattern.sv
- tests/chapter-12/12.6.1--casez_pattern.sv
- tests/chapter-12/12.6.2--if_pattern.sv
- tests/chapter-12/12.6.3--conditional_pattern.sv
- tests/chapter-12/12.7.1--for.sv
- tests/chapter-12/12.7.2--repeat.sv
- tests/chapter-12/12.7.3--foreach.sv
- tests/chapter-12/12.7.4--while.sv
- tests/chapter-12/12.7.5--dowhile.sv
- tests/chapter-12/12.7.6--forever.sv
- tests/chapter-12/12.8--break.sv
- tests/chapter-12/12.8--continue.sv
- tests/chapter-12/12.8--return.sv
- tests/chapter-12/12.8--return_val.sv
Current status:
Depends on #43
> Add tests for chapter "Procedural programming statements"

- .gitmodules
- .travis.yml
- README.md
- runners/zachjs-sv2v
- tools/runners.mk
> Add sv2v runner

- .travis.yml
PR to test some travis ccache settings.
> Manually force ccache usage

- .gitmodules
- Makefile
- conf/lrm.conf
- generators/swerv
This adds SweRV core as a test with its separate tag `swerv`
Closes #60 
Depends #67
> Add SweRV as a test

- Makefile
- tools/runner
> Provide output log path as parameter to tools/runner

- tests/chapter-12/12.7.5--dowhile.sv
>  missing ; after while loop

- tests/chapter-8/8.8--typed_constructor_param.sv
> Wrong parametrized method call syntax

- tests/chapter-12/12.6.3--conditional_pattern.sv
> No parenthesis after matches

- .gitmodules
- conf/lrm.conf
- generators/fx68k
> Add FX68K core as test

- Makefile
- tools/runners.mk
[ this is same as #139 but with commit properly signed-off]
> Remove rule-silencing; use $(MAKE) where possible

- conf/generators/meta-path/yosys-asicworld.json
- conf/generators/meta-path/yosys-errors.json
- conf/generators/meta-path/yosys-memories.json
- conf/generators/meta-path/yosys-simple.json
- conf/generators/meta-path/yosys-sva.json
- conf/generators/meta-path/yosys-svinterfaces.json
- conf/lrm.conf
- generators/path_generator
- generators/yosys_hana
Imported tests:
Closes #58
This also adds a generic `.json` config driven generator for cases where test wrapper must be generated for each file in a directory
> Import tests from Yosys

- conf/generators/templates/integers.json
> tests: place signing specifier after type in integer tests

- conf/report/report-template.html
- conf/report/report.css
- tools/sv-report
This PR adds a footer to the report with the total number of tests passed and the total number of tags for which all of the tests passed.
Closes #164
> Add report summary

- tests/generic/class/class_test_35.sv
- tests/generic/member/class_member_test_16.sv
- tests/generic/member/class_member_test_3.sv
> Can't mix extern and automatic qualifiers

- tests/chapter-6/6.16.11--string_itoa.sv
- tests/chapter-6/6.16.12--string_hextoa.sv
- tests/chapter-6/6.16.13--string_octtoa.sv
- tests/chapter-6/6.16.14--string_bintoa.sv
- tests/chapter-6/6.16.15--string_realtoa.sv
- tests/chapter-6/6.16.2--string_putc.sv
As pointed out by @alainmarcel in #122
> tests: fix string function calls in chapter 6

- conf/report/report-template.html
- conf/report/report.js
Automatically open the very first tab after clicking any cell on the report.
It would be nice to have something similar for the test source files, but it will be harder to implement because the files are currently not stored in the python dict.
> report: automatically open the first tab after clicking cell

- conf/report/report.js
> report: fix close button

- tests/generic/preproc/preproc_test_10.sv
- tests/generic/preproc/preproc_test_11.sv
- tests/generic/preproc/preproc_test_12.sv
- tests/generic/preproc/preproc_test_13.sv
- tests/generic/preproc/preproc_test_9.sv
> Malformed macro definitions

- tools/runners/tree_sitter_verilog.py
Current tree-sitter-verilog runner log output is not that useful, this aims to fix that
New output looks like this:
```
third_party/tools/yosys/tests/sva/basic01.sv:9:35: error: node type: ERROR
third_party/tools/yosys/tests/sva/basic01.sv:11:35: error: node type: ERROR
third_party/tools/yosys/tests/sva/basic01.sv:13:35: error: node type: ERROR
```
> runners: better tree-sitter-verilog error messages

- tests/generic/typedef/typedef_test_21.sv
- tests/generic/typedef/typedef_test_23.sv
> Illegal typedef base type

- .travis.yml
- Makefile
- tools/sv-report
This way this dir can be directly deployed by Travis and the process
will be more consistent between local and CI deployments.
Fixes #220
> Create the report in deploy dir

- .dependabot/config.yml
> Fix dependabot submodules path

- .gitmodules
- .travis.yml
- README.md
- tools/runners.mk
- tools/runners/sv_parser.py
I want to append sv-parser which is a SystemVerilog parser written in Rust.
https://github.com/dalance/sv-parser
> Add sv-parser

- .travis.yml
- Makefile
- tools/sv-report
Fixes #259
Signed-off-by: Tomasz Gorochowik <tgorochowik@gmail.com>
> Rename deploy dir to report

- conf/report/log-template.html
- tools/sv-report
> Escape html in the log template

- tools/runners/sv_parser.py
> Add url of sv_parser

- conf/report/report-template.html
- conf/report/report.js
This PR makes it possible to link directly to the test case, links use the following format: `index.html#Sv2v_zachjs|5.7.2|number_test_71`
This also makes it possible to switch between tools and keep open the same test case
Closes #271
Closes #272
> report: add support for linking to testcases and chapters inside report

- generators/ariane
- tools/sv-report
It appears that some files were not included in formatting fixes that were part of #277
This PR aims to fix that
> ci: fix python code formatting

- .gitmodules
- generators/scr1
> Add SCR1 RISC-V core as a test

- tools/sv-report
Depends #232
Fixes #233
Depends #288
> report: fix issue with not linking to some source files

- tests/generic/member/class_member_test_13.sv
> Fix generic class test 13

- .gitmodules
- generators/taiga
This adds [Taiga](https://gitlab.com/sfu-rcl/Taiga) core testcase.
Closes #275
Depends #288
> Add Taiga RISC-V core as a test

- tests/chapter-11/11.10.3--empty_string.sv
> tests: fix issue with $assert() in empty_string test

- conf/report/log-template.html
- conf/report/report-template.html
- tools/runner
- tools/sv-report
Work in progress to solve #237
> Measure time needed to complete all the tests

- conf/lrm.conf
> Add missing tags

- conf/generators/meta-path/utd-systemverilog.json
- generators/path_generator
> generators: add support for blacklisting

- generators/path_generator
> generators: path_generator: fix incdirs generation

- README.md
This PR aims to add a short list of steps for anyone that wants to add a new tool
Closes #326
> doc: add short guide on adding a new tool to the test suite

- README.md
> doc: add a short guide on importing existing tests

- README.md
> doc: add a short guide on adding new test cases

- README.md
> doc: reorder how-to sections

- .gitmodules
- conf/generators/meta-path/basejump.json
> Add BaseJump STL as a test

- conf/requirements.txt
- generators/ariane
- generators/fx68k
- generators/ibex
- generators/scr1
- generators/swerv
- generators/taiga
- tools/BaseRunner.py
- tools/runner
- tools/sv-report
Some tools seem to be stall at some tests.
This PR add timeout to each process.
> Add timeout

- tools/runners.mk
As suggested by the author in #336
> Build slang in release mode

- conf/report/report-template.html
This PR fixes the sort order of some columns.
> Fix sort order

- conf/lrm.conf
- tests/chapter-14/14.3--clocking-block-signals.sv
- tests/chapter-14/14.3--clocking-block.sv
- tests/chapter-14/14.3--default-clocking-block.sv
- tests/chapter-14/14.3--global-clocking-block.sv
> tests: add tests for parsing clocking block declarations

- conf/generators/templates/force-assignments.json
- conf/lrm.conf
- tests/chapter-10/10.3.1--net-decl-assignment.sv
- tests/chapter-10/10.3.2--cont-assignment.sv
- tests/chapter-10/10.3.3--cont-assignment-delay.sv
- tests/chapter-10/10.3.3--cont-assignment-net-delay.sv
- tests/chapter-10/10.4.1--blocking-assignment.sv
- tests/chapter-10/10.4.2--non-blocking-assignment.sv
- tests/chapter-10/10.6.1--assign-deassign.sv
- tests/chapter-10/10.6.2--force-release.sv
> tests: add tests for various assignment types

- README.md
- conf/environment.yml
- tools/BaseRunner.py
- tools/runners.mk
- tools/runners/moore.py
Add the [moore] compiler to the suite of tools. Fixes #339.
[moore]: https://github.com/fabianschuiki/moore
> Add moore compiler

- conf/lrm.conf
- tests/chapter-13/13.3--task.sv
- tests/chapter-13/13.3.1--task-automatic.sv
- tests/chapter-13/13.3.1--task-static.sv
- tests/chapter-13/13.4--function.sv
- tests/chapter-13/13.4.1--function-return-assignment.sv
- tests/chapter-13/13.4.1--function-return.sv
- tests/chapter-13/13.4.1--function-void-return.sv
- tests/chapter-13/13.4.2--function-automatic.sv
- tests/chapter-13/13.4.2--function-static.sv
- tests/chapter-13/13.4.3--const-function.sv
- tests/chapter-13/13.4.4--fork-invalid.sv
- tests/chapter-13/13.4.4--fork-valid.sv
> tests: add tests for tasks and functions

- conf/lrm.conf
- tests/chapter-26/26.2--package-decl.sv
- tests/chapter-26/26.3--package-ref.sv
> tests: add tests for package declarations and referencing

- conf/lrm.conf
- tests/chapter-15/15.4--mailbox-blocking.sv
- tests/chapter-15/15.4--mailbox-non-blocking.sv
> tests: add tests for mailbox operations

- conf/lrm.conf
- tests/chapter-21/21.2--display.sv
- tests/chapter-21/21.2--monitor.sv
- tests/chapter-21/21.2--strobe.sv
- tests/chapter-21/21.2--write.sv
- tests/chapter-21/21.3--fdisplay.sv
- tests/chapter-21/21.3--feof.sv
- tests/chapter-21/21.3--ferror.sv
- tests/chapter-21/21.3--fflush.sv
- tests/chapter-21/21.3--fgetc.sv
- tests/chapter-21/21.3--fgets.sv
- tests/chapter-21/21.3--file.sv
- tests/chapter-21/21.3--fmonitor.sv
- tests/chapter-21/21.3--fpos.sv
- tests/chapter-21/21.3--fread.sv
- tests/chapter-21/21.3--fscanf.sv
- tests/chapter-21/21.3--fstrobe.sv
- tests/chapter-21/21.3--fwrite.sv
- tests/chapter-21/21.3--sscanf.sv
- tests/chapter-21/21.3--ungetc.sv
- tests/chapter-21/21.4--readmemb.sv
- tests/chapter-21/21.4--readmemh.sv
- tests/chapter-21/21.6--test.sv
- tests/chapter-21/21.6--value.sv
- tests/chapter-21/21.7--dumpfile.sv
- tests/chapter-21/21.7--dumpports.sv
> tests: add tests for IO tasks/functions

- conf/lrm.conf
- tests/chapter-16/16.12--property-disable-iff.sv
- tests/chapter-16/16.12--property-disj.sv
- tests/chapter-16/16.12--property-iff.sv
- tests/chapter-16/16.12--property-prec.sv
- tests/chapter-16/16.12--property.sv
- tests/chapter-16/16.2--assert-final.sv
- tests/chapter-16/16.2--assert.sv
- tests/chapter-16/16.2--assert0.sv
- tests/chapter-16/16.2--assume-final.sv
- tests/chapter-16/16.2--assume.sv
- tests/chapter-16/16.2--assume0.sv
- tests/chapter-16/16.2--cover-final.sv
- tests/chapter-16/16.2--cover.sv
- tests/chapter-16/16.2--cover0.sv
> tests: add selected assertion tests

- conf/lrm.conf
- tests/chapter-24/24.3--program.sv
> tests: add program construct test

- conf/lrm.conf
- tests/chapter-23/23.2--macromodule-definition.sv
- tests/chapter-23/23.2--module-definition.sv
> Add module/macromodule tests

- conf/lrm.conf
- tests/chapter-25/25.3-interface.sv
> Add interface tests

- generators/blackparrot
Signed-off-by: Naoya Hatta <dalance@gmail.com>
> Increase timeout of blackparrot

- tests/chapter-22/22.5.1--define-expansion_10.sv
- tests/chapter-22/22.5.1--define-expansion_11.sv
- tests/chapter-22/22.5.1--define-expansion_12.sv
- tests/chapter-22/22.5.1--define-expansion_13.sv
- tests/chapter-22/22.5.1--define-expansion_14.sv
- tests/chapter-22/22.5.1--define-expansion_15.sv
- tests/chapter-22/22.5.1--define-expansion_16.sv
- tests/chapter-22/22.5.1--define-expansion_17.sv
- tests/chapter-22/22.5.1--define-expansion_18.sv
- tests/chapter-22/22.5.1--define-expansion_21.sv
- tests/chapter-22/22.5.1--define-expansion_25.sv
- tests/chapter-22/22.5.1--define-expansion_26.sv
- tests/chapter-22/22.5.1--define-expansion_9.sv
This PR fixes syntax error of define-expansion_*.
> Fix define testcases

- README.md
- tools/runners/Verilator.py
Minor commentary - Update Verilator URL and clean some trailing slashes.
> Update Verilator URL

- .github/kokoro/run.sh
- .github/kokoro/steps/hostsetup.sh
- Makefile
Run everything that can be run in parallel, then output a single failure.
> kokoro: Run everything, then display first failure.

- .gitmodules
- conf/environment.yml
- tools/runners.mk
- tools/runners/Verible.py
Fixes #424 
Adding a WIP label until we get a proper Conda package for verible. However with this PR it is possible to test Verible locally.
> Add verible

- README.md
> Add verible to README

- tools/BaseRunner.py
> Fixing formatting.

- .github/kokoro/run.sh
- .github/travis/install.sh
- .travis.yml
- Makefile
- conf/environment.yml
- tools/runner
* Move Travis CI install to a `install.sh` script.
* Use `requirements.txt` inside `environment.yml`.
* Use the `environment.yml` for installing on Travis and Kokoro.
* Rework how `RUNNER` is set which fixes #483.
> Updating CI environment installing.

- conf/lrm.conf
> Add missing database tags

- conf/lrm.conf
Adding this missing description should help with #500 but the real issue still remains
> report: add chapter 10.3 desc to lrm.conf

- tests/generic/desc/desc_test_0.sv
- tests/generic/desc/desc_test_1.sv
- tests/generic/desc/desc_test_10.sv
- tests/generic/desc/desc_test_11.sv
- tests/generic/desc/desc_test_12.sv
- tests/generic/desc/desc_test_13.sv
- tests/generic/desc/desc_test_14.sv
- tests/generic/desc/desc_test_15.sv
- tests/generic/desc/desc_test_16.sv
- tests/generic/desc/desc_test_17.sv
- tests/generic/desc/desc_test_18.sv
- tests/generic/desc/desc_test_2.sv
- tests/generic/desc/desc_test_3.sv
- tests/generic/desc/desc_test_4.sv
- tests/generic/desc/desc_test_5.sv
- tests/generic/desc/desc_test_6.sv
- tests/generic/desc/desc_test_7.sv
- tests/generic/desc/desc_test_8.sv
- tests/generic/desc/desc_test_9.sv
- tests/generic/empty/empty_test_0.sv
- tests/generic/empty/empty_test_1.sv
- tests/generic/empty/empty_test_2.sv
- tests/generic/empty/empty_test_3.sv
- tests/generic/empty/empty_test_4.sv
- tests/generic/empty/empty_test_5.sv
- tools/BaseRunner.py
- tools/runners/Verilator.py
Fix to ignore some Verilator warnings.
Fix showing tool version when tool is script.
> Fix version from scripts, and some Verilator warnings

- .travis.yml
It appears to be causing failures on some pull requests.
> travis: Remove pip cache.

- .gitmodules
- .travis.yml
- conf/environment.yml
- tools/runners.mk
- tools/runners/Surelog.py
> Add Surelog to tested tools.

- tests/chapter-8/8.25--parametrized_class_extend.sv
- tests/chapter-8/8.5--parameters.sv
- tests/chapter-8/8.5--properties_enum.sv
- tests/chapter-8/8.8--typed_constructor.sv
- tests/chapter-8/8.8--typed_constructor_param.sv
This fixes a bunch of tests with typos etc to be legal.
> Fix chapter 8 broken tests.

- .dependabot/config.yml
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> dependabot: automerge all the deps

- .dependabot/config.yml
> dependabot: fix config

- .gitmodules
- conf/lrm.conf
- generators/rsd
This PR adds RSD RISC-V core to tests.
https://github.com/rsd-devel/rsd
> Add RSD RISC-V core

- tests/chapter-20/20.6--isunbounded.sv
Fix test to properly check return value.
> Fix $unbounded test

- tests/chapter-22/22.4--include_via_define.sv
Create new test described in pull 517.
> Add tests/chapter-22/22.4--include_via_define.sv.

- generators/ibex
Not sure how to sync this with #590 which is updating the Ibex revision.
Included a commit for Ibex bump.
> Fix Ibex source path

- tests/chapter-8/8.14--override_member.sv
> Fix syntax error

- tools/runners.mk
Signed-off-by: Wojciech Tatarski <wtatarski@antmicro.com>
> Fixed name of the Slang binary output

- conf/generators/earlgrey/earlgrey.src
> Earlgrey test has incomplete verilog command line

- tools/BaseRunner.py
> Add the tool invocation commandline to the logfile.

- tools/runners.mk
> Use the verible install build command.

- README.md
Makes it possible to refer to "steps 1-2", etc.
> README: Converting to numbered lists

- README.md
A number of the tools have submodules themselves.  I was unable to build all of the tools until I did this.
> Recursive submodule init instructions

- tools/runners/Verilator.py
> Make verilator script more verbose

- conf/environment.yml
- conf/requirements.txt
- tools/BaseRunner.py
CI in master fails because there is a new yapf version.
Reformat the code to fix that for now and force constant yapf version to prevent this from happening in the future.
> Yapf changes

- conf/environment.yml
> Add ccache to dependencies

- tests/chapter-20/20.9--isunknown.sv
Fix test problems:
Fix 20.9--isunknown.sv: Fix width and work with 2-state simulation.
> Fix 6.20.2.1--parameter_unbounded.sv and 20.9--isunknown.sv

- generators/swerv
Hopefully this will allow Surelog to pass this test.
> Increase SweRV timeout to 3 minutes

- conf/report/report.js
> Fix typo in js variable name

- conf/lrm.conf
- tests/chapter-16/16.12--property-interface-prec-uvm.sv
- tests/chapter-16/16.12--property-interface-uvm-fail.sv
- tests/chapter-16/16.12--property-interface-uvm.sv
- tests/chapter-16/16.12--property-prec-uvm-fail.sv
- tests/chapter-16/16.12--property-prec-uvm.sv
- tests/chapter-16/16.12--property-uvm-fail.sv
- tests/chapter-16/16.12--property-uvm.sv
- tests/chapter-16/16.17--expect-uvm.sv
- tests/chapter-16/16.17--expect.sv
- tests/chapter-16/16.2--assert-final-uvm.sv
- tests/chapter-16/16.2--assert-uvm.sv
- tests/chapter-16/16.2--assert0-uvm.sv
- tests/chapter-16/16.2--assume-uvm-fail.sv
- tests/chapter-16/16.2--assume-uvm.sv
- tests/chapter-16/16.7--sequence-uvm-fail.sv
- tests/chapter-16/16.7--sequence-uvm.sv
- tests/chapter-16/16.7--sequence.sv
This adds simulation assertion tests that use UVM.
Depends on #837
> Add basic simulation tests for chapter 16 (Assertions)

- tests/chapter-9/9.4.2--event_control_sim.sv
- tests/chapter-9/9.4.2--event_control_sim_minimal.sv
> Add a simple event driven simulation test

- .gitmodules
- .travis.yml
- conf/environment.yml
- tests/chapter-10/10.3.1--one-net.sv
- tools/runners.mk
- tools/runners/UhdmVerilator.py
- tools/runners/UhdmYosys.py
Marking as WIP as we don't have a conda package for this yet. Basically almost all of the tests fail for now. I've added a very simple simulation test with a one-net assignment as we really lack such simple simulation tests (the simplest tests are not marked for simulation).
Depends on: https://github.com/SymbiFlow/conda-packages/pull/97
> Add uhdm-integration runners

- README.md
Partially addresses #913 (until a proper solution is implemented).
> Add dependencies install step

- generators/path_generator
As suggested by @piotr-binkowski
Fixes #915
> Clear should_fail_because for each template run

- conf/generators/meta-path/basejump.json
- tests/testbenches/uvm_agent_active.sv
- tests/testbenches/uvm_agent_env.sv
- tests/testbenches/uvm_agent_passive.sv
- tests/testbenches/uvm_driver_sequencer_env.sv
- tests/testbenches/uvm_monitor_env.sv
- tests/testbenches/uvm_scoreboard_env.sv
- tests/testbenches/uvm_scoreboard_monitor_agent_env.sv
- tests/testbenches/uvm_scoreboard_monitor_env.sv
> Adapt a few timeouts that are hit and miss on the CI

- conf/report/report-template.html
- tools/sv-report
The multiprocessing seems to run into trouble on the
CI machines when transferring large amounts of data.
This is at the expense of making the html template more ugly though...
> Reduce the amount of data generated when collecting logs.

- tests/chapter-13/13.4.2--function-recursive.sv
A test to validate recursive automatic functions. Contains a recursive implementation of factorial and 5 test cases.
> Recursive function test

- .github/travis/install.sh
- .gitmodules
- .travis.yml
- conf/environment.yml
- tools/runners.mk
- tools/runners/Antmicro_yosys.py
PR adds yosys as a runner from this repo: https://github.com/antmicro/yosys/tree/ibex-wip-symbiflow
> Add new yosys runner

- generators/earlgrey
- generators/ibex
> Ibex scan for source files dynamically

- tools/runners/Yosys.py
- tools/runners/YosysSv.py
This allows us to cat the yosys script. This should be useful for
debugging and reproducing the tests.
> Add a wrapper script for yosys runners

- conf/lrm.conf
- conf/report/report-template.html
- conf/report/report.css
- tools/sv-report
The test suites descriptions are now clickable (where applicable):
Fixes #934
> Clickable test suites

- tools/runners/Icarus.py
- tools/runners/Slang.py
- tools/runners/UhdmVerilator.py
- tools/runners/UhdmYosys.py
- tools/runners/Yosys.py
- tools/runners/YosysSv.py
> Supply the remaining runners with defines

- tools/runners/Slang.py
Fixes a bug introduced in #1000.
> Fix incdirs and defines for slang

- tests/chapter-11/11.10--string_bit_array-sim.sv
Fix obvious assertion mistake.
> Fix expected value for 11.10--string_bit_array-sim.sv

- conf/generators/ariane/ar_src.src
This PR fixes missing files in ar_src.src.
Signed-off-by: Naoya Hatta <dalance@gmail.com>
> Fix missing file in ar_src

- tests/chapter-9/9.2.2.1--always.sv
> Remove deadlock from `always` test

- conf/generators/meta-path/basejump.json
- generators/path_generator
Fixes #1160 
@MikePopoloski could you please take a look if this solves the issue for you?
> Generate a fake topmodule for basejump tests

- generators/ivtest
> Add back ivtests that now have a keyword version specified

- tools/runners/sv_parser.py
This PR adds defines support to sv_parser.
> Add defines support to sv_parser

- generators/ivtest
This cleans up a couple of the tests in ivtest so they work as expected
> Cleanup some ivtest tests

- tests/chapter-7/arrays/associative/arguments.sv
Signed-off-by: Wilson Snyder <wsnyder@wsnyder.org>
> Fix arguments.sv broken test condition

- tests/chapter-18/18.5.8.2--array-reduction-iterative-constraints_0.sv
- tests/chapter-25/25.3-interface.sv
- tests/chapter-7/arrays/packed/variable-slice-zero.sv
- tests/chapter-9/9.7--process_cls_kill.sv
- tests/chapter-9/9.7--process_cls_self.sv
- tests/chapter-9/9.7--process_cls_suspend_resume.sv
- tests/generic/class/class_test_25.sv
Just fixes a few bugs in random tests that slang caught.
Signed-off-by: MikePopoloski <mike@popoloski.com>
> Fix various invalid tests

- generators/ivtest
> Update ivtest/icarus and the control file

- conf/requirements.txt
- generators/ariane
Parse the Ariane Makefile to get up-to-date file list.
> Fix file list for Ariane core

- conf/fusesoc-configs/ibex.yml
Update the fusesoc command for ibex core.
> Fix fusesoc command for ibex core

- generators/black-parrot
Title, fixes some of the Verilator tests
> Bumping BlackParrot and updating generator

- tools/runners/Icarus.py
Update the Icarus runner version code to get the full version information.
> Get the full version for Icarus

- conf/fusesoc-configs/swerv.yml
Add missing swerv config file for fusesoc.
Ref: https://github.com/SymbiFlow/sv-tests/pull/1300
> Add swerv config file for fusesoc

- .github/kokoro/periodic.cfg
Ref: https://github.com/SymbiFlow/sv-tests/pull/1329#issuecomment-778697671
> kokoro: add periodic.cfg

- .github/workflows/summary.sh
This commit fixes error about broken pipe, for example:
https://github.com/SymbiFlow/sv-tests/runs/1903030447?check_suite_focus=true#step:6:2578
Signed-off-by: Joanna Brozek <jbrozek@antmicro.com>
> summary: simplify adding header

- .github/workflows/sv-tests-ci.yml
- conf/fusesoc-configs/earlgrey.yml
- conf/fusesoc-configs/ibex-sim.yml
- conf/fusesoc-configs/ibex-synth.yml
- conf/fusesoc-configs/ibex.yml
- conf/fusesoc-configs/swerv.yml
- generators/fusesoc
- tools/BaseRunner.py
- tools/report_analyzer.py
- tools/runner
- tools/runners/UhdmVerilator.py
- tools/runners/UhdmYosys.py
- tools/sv-report
This PR fixes building ibex-core using uhdm-yosys.
> uhdm-yosys: fix testing ibex-core

- tests/chapter-11/11.3.6--assign_in_exp-sim.sv
- tests/chapter-11/11.3.6--assign_in_exp.sv
- tests/chapter-11/11.3.6--assign_in_expression-sim.sv
- tests/chapter-11/11.3.6--assign_in_expression.sv
- tests/chapter-11/11.3.6--assignment_in_expression-sim.sv
- tests/chapter-11/11.3.6--assignment_in_expression.sv
- tests/chapter-11/11.3.6--two_assign_in_expr-sim.sv
- tests/chapter-11/11.3.6--two_assign_in_expr.sv
> Added tests for 11.3.6

- generators/rsd
This fixes the RSD generator to allow tools that actually check correctness of code to elaborate the design.
> Fix the RSD generator

- conf/report/report-template.html
- conf/report/report.css
Added 45-degree angle and made the headline fixed
https://user-images.githubusercontent.com/44160152/115524316-9f42e200-a2ab-11eb-9020-6915bf686257.mp4
> Fixed variable width columns

- generators/ariane
Improve generator for Ariane core to pass tests for moore_parse and sv_parser tools.
> Ariane core: Improve generator to pass tests for moore_parse and sv_parser 

- tools/sv-report
> Improve error message

- conf/report/report-template.html
- conf/report/report.css
Signed-off-by: Prahitha Movva <prahitha.movva03@gmail.com>
fixes #1469 and #1470
> fixed first column of the table

- tools/runners/Surelog.py
Signed-off-by: Alain Dargelas <alain.dargelas@gmail.com>
> lowmem option for Surelog

- generators/tnoc
Signed-off-by: Taichi Ishitani <taichi730@gmail.com>
This PR is to fix #1551.
I've confirmed there are no errors by using VCS.
> fix TNoC wrapper error

- .github/workflows/update_report.sh
> Change deploy URL to the new results repo

- README.md
Update github links, remove kokoro badge.
> Post migration URLs update

- .github/workflows/sv-tests-ci.yml
> Add daily builds

- conf/report/report-template.html
> Fix URLs in the report

- .github/workflows/sv-tests-ci.yml
- .github/workflows/sv-tests-code-quality.yml
This PR:
* Moves code quality checks to a separate conf file (and gives it separate triggers)
* Cancels previous workflows (for example if there are two worflows running for different commits on the same branch)
> CI cleanup

- tools/sv-report
Signed-off-by: Prahitha Movva <prahitha.movva03@gmail.com>
> change env variable

- conf/report/report-template.html
- conf/report/report.css
- tools/sv-report
Note: This is a WIP and does not have the filtering functionality yet (the applyFilter function has to be implemented). Ideally, the test types should also not be hard-coded (will work on it). 
Any suggestions on how to store the selected options properly would be really helpful. Since there are a lot of things to consider, like:
- selecting the percentage first and then the tool vs selecting the tool first and then the percentage (also, how to store these percentages for each tool? would it be a dict?)
- updating the values appropriately if someone goes back to change the values in a previous dropdown (would changing the values at that index be a good approach?) etc
Thanks!
https://user-images.githubusercontent.com/44160152/121487940-372d9400-c9f0-11eb-84bd-a70ad57e7c6c.mp4
> ui for filtering; no functionality yet

- conf/report/report-template.html
Signed-off-by: Prahitha Movva <prahitha.movva03@gmail.com>
> fix variable width column issue

- .gitmodules
- tools/runners.mk
- tools/runners/UhdmYosys.py
This PR updates ``uhdm-yosys`` runner to use ``uhdm`` frontend as a plugin to yosys.
> uhdm-yosys: update runner to use uhdm as a plugin

- .github/workflows/comment-pr.yml
- .github/workflows/sv-tests-ci.yml
Keep data about new failures, new passes and full csv files that were
used for comparison.
> Make PR artifacts more useful

- .github/workflows/install.sh
- .github/workflows/sv-tests-ci.yml
- conf/environment.yml
> CI: conda: use only channels that were used to built package

- conf/generators/templates/assignment-sim.json
- conf/generators/templates/encapsulation-success.json
- conf/generators/templates/equality.json
- conf/generators/templates/logical-equiv.json
- conf/generators/templates/logical-impl.json
- conf/generators/templates/logical.json
- conf/generators/templates/operators-sim.json
- conf/generators/templates/sampled-functions-gclk.json
- conf/generators/templates/sampled-functions.json
- conf/generators/templates/simple-logical.json
- conf/generators/templates/simple-operators-sim.json
- conf/generators/templates/trig-functions.json
- conf/generators/templates/wildcard-const.json
- conf/generators/templates/wildcard.json
This commit:
* Adds elaboration to types where applicable
* Fixes formatting of some of the configs
> Update template tests

- tools/BaseRunner.py
> Allow the tools to use more memory

- generators/black-parrot
- tools/runners/Surelog.py
Signed-off-by: Alain Dargelas <alain.dargelas@gmail.com>
> Surelog runner options and memory limit for black-parrot

- .github/workflows/sv-tests-ci.yml
> Use ccache to speedup builds

- .gitmodules
CC @alaindargelas 
Fixes #1868
> Bump surelog

- .gitmodules
> Fix Surelog submodule

- .github/workflows/dependabot-automerge.yml
via: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
> Add dependabot automerge

- conf/meta-tags.conf
- conf/report/filter.js
- conf/report/report-template.html
- conf/report/report.css
- conf/report/report.js
* Code cleanup.
* Fixed headers implemented in CSS (better performance).
* Minor layout/visual fixes, like:
* fixed horizontal position of the filter section,
* uniform size of test result and summary cells,
* aligned column header labels,
* header links are now slightly highlighted on hover to signal whether
the link or the header (both of which trigger different actions)
is currently under the cursor,
* header links' underline has been moved a bit down to not cover `_`,
* removed superfluous bottom line under the last table footer row.
New / Old:
> Cleanup and optimize report template. 

- .github/workflows/summary.sh
- .github/workflows/sv-tests-ci.yml
> Move history out of OUT_DIR

- tests/generic/typedef/typedef_test_28__bad.sv
> Fix name of typedef_test_28__bad test

- .gitmodules
> Fix verible submodule URL

- conf/requirements.txt
> Pin edalize version

- .github/workflows/sv-tests-ci.yml
> Force https:// instead of git:// when accessing github

- generators/black-parrot
> Move black parrot to cores group

- tools/runners.mk
- tools/runners/UhdmYosys.py
- tools/runners/VanillaYosysUhdmPlugin.py
This PR also fixes local update of ``yosys-uhdm``.
> Fix building Ibex using UhdmYosys

- tools/runners/UhdmVerilator.py
- tools/runners/UhdmYosys.py
- tools/runners/VanillaYosysUhdmPlugin.py
> Add -lowmem to all tools using surelog for relevant tests

- .github/workflows/sv-tests-ci.yml
- conf/fusesoc-configs/earlgrey-sim.yml
- conf/fusesoc-configs/ibex-sim.yml
- conf/fusesoc-configs/swerv-sim.yml
- generators/fusesoc
- tools/BaseRunner.py
- tools/runners/Verilator.py
Similar changes should be made also for UhdmVerilator runner. I'll do it in another PR.
> Add simulation_without_run mode

- generators/ivtest
Add three tests to the exclusion list; comments in the file explain why.
> Exclude a few of the new ivtests

- .github/workflows/sv-tests-ci.yml
- tools/runners.mk
This should fix the CI which is currently red.
> Build verible with host flex and bison

- generators/ivtest
> Exclude one more case from ivtest

- .github/workflows/sv-tests-ci.yml
Should fix the red CI on the main branch.
> Make sure to generate the markdown summary for all pipelines

- tests/chapter-10/10.6.2--force-release.sv
This improves the test to handle the more complex and common case of hierarchical forcing.
> 10.6.2--force-release: Test hierarchical force/release.

- tools/runners/UhdmYosys.py
- tools/runners/Yosys.py
- tools/sv-report
Marking as draft for now to see how it influences the report generation speed.
Ref #2749
> Improve Summary step speed

- README.md
We no longer use conda in sv-tests.
> Remove the deprecated conda info from README

- tools/runners/Slang.py
Signed-off-by: MikePopoloski <mike@popoloski.com>
> slang runner: set a default timescale

- tests/chapter-5/5.10-structures.sv
- tests/chapter-5/5.12-attributes-case.sv
- tests/chapter-5/5.12-attributes-conditional.sv
- tests/chapter-5/5.12-attributes-operator.sv
- tests/chapter-5/5.13-builtin-methods-strings.sv
- tests/chapter-5/5.7.1--integers-left-padding-bit.sv
- tests/chapter-5/5.7.1--integers-underscores.sv
- tests/chapter-5/5.7.2-real-constants-illegal.sv
- tests/chapter-5/5.7.2-real-constants.sv
- tests/chapter-5/5.9-string-assignment.sv
- tests/chapter-5/5.9-string-basics.sv
- tests/chapter-5/5.9-string-broken-line.sv
Noticed some random semicolons in some test files for chapter 5 that probably should not be there
> Remove some awkwardly placed redundant semicolons

- generators/scr1
> Fix scr1 incdirs

- .gitmodules
- conf/lrm.conf
- generators/rggen
Hi,
I've update the top module for RgGen sample modules.
This is to fix #4776.
> update RgGen sample

- tools/runners.mk
Seems some deps updated in the background and broke the build again.
> Bump rustc for moore

- .github/workflows/sv-tests-ci.yml
- .gitmodules
- conf/fusesoc-configs/veer-eh1-sim.yml
- conf/fusesoc-configs/veer-eh1-synth.yml
- conf/lrm.conf
- generators/veer-config
SweRV is officially renamed to VeeR, this PR renames it in sv-tests. There are also new tests for VeeR EL2 core.
> Rename SweRV to VeeR & add VeeR EL2

- .github/workflows/sv-tests-ci.yml
- .gitmodules
- conf/fusesoc-configs/earlgrey-synth.yml
- conf/fusesoc-configs/ibex-synth.yml
- conf/fusesoc-configs/veer-eh1-synth.yml
- generators/veer-config
- tools/runners.mk
- tools/runners/SynligYosys.py
The Yosys SV plugin has been rebranded to [Synlig](https://github.com/chipsalliance/synlig).
> Rename UhdmYosys to SynligYosys

- tools/runners/Yosys.py
* For simulation tests, suppress display task output from elaboration
* More robust detection of top module by fallback to -auto-top
* Added 'clean' pass to avoid passing unused memory to memory_collect
> Minor enhancements to the Yosys runner

- .github/workflows/sv-tests-ci.yml
- .gitmodules
- tools/runners.mk
- tools/runners/yosys_slang.py
Hello everyone,
[yosys-slang](https://github.com/povik/yosys-slang) is a minor experiment of building a Yosys frontend on top of Slang. Having it on your dashboard might help gauge where it stands, and aid its development (should there be any). Please consider merging this in.
> Add yosys-slang as a new tool to test

- generators/rggen
fix chipsalliance/sv-tests#5800
> Fix RgGen test

- conf/requirements.txt
The CI fails with the latest version
Fixes #6032
> Freeze simplestat version

- .github/workflows/sv-tests-ci.yml
Speeds up cloning and helps avoid hitting rate limits.
> Do shallow clones in CI

- .github/workflows/report.sh
- .github/workflows/summary.sh
- .github/workflows/sv-tests-ci.yml
- .github/workflows/update_report.sh
Fixes issues with missing VeeR dependencies.
> Fix VeeR dependencies

- .github/dependabot.yml
Restore the dependabot config.
Reverts #7082.
> Restore dependabot config

- tests/chapter-6/6.23--localparam_type_decl.sv
Test declaring a type with a localparam
IEEE Std 1800™-2023 chapter 6.23
> Test declaring a type with a localparam

- .github/workflows/lint-review.yml
- .github/workflows/sv-tests-ci.yml
- .github/workflows/sv-tests-code-quality.yml
This adds a button in the github UI under each action workflow to allow it to be run when pressed.
> Add github workflow_dispatch trigger
