chipsalliance/sv-tests

README.md, runners/odin
Odin wrapper uses external architecture definition and configuration files but it is possible to use odin
without architecture file and with configuration specified via commandline.
This significantly simplifies odin runner and makes it less dependent on where the odin executable is located.
=> Make odin wrapper work without external XML files

conf/report-template.html, tools/sv-report
The result of the report generator is pretty much the same, but here is what changed and why:
* the `pandas` dependency was dropped - it was only used to generate the raw html table - we should be doing that by hand (with templates) to be able to fill all the individual cells with more details about the testcases and their results - this is a foundation for that.
Additionally without it it is easier to keep the formatting (colors etc) in the template instead of the python code.
* Cleaned up the template - the initial formatting was pretty inconsistent - this PR fixes that and adds a vim modeline at the begging to help avoid that in the future.
=> Make the report generator extensible

conf/report-template.html, tools/sv-report
Users can now click the cells which indicate that there are some test
results. Clicking them will show an overlay with the test results and
test logs.
=> report: show logs upon clicking results cell

conf/report-template.html
The following things were improved:
* The cells that contain any test result now have a small dotted border.
This helps to see what is what when the table header stops being
visible.
* All the cells have now the same width (earlier it was aligned to the
tool name).
=> report: styling improvements

Makefile, tools/runner
This significantly reduces the time of generating the targets given
there is a large number of tests.
For example for ~300 tests, the generation alone takes about 1 minute
and 30 seconds.
With this change it is almost instant.
=> Improve Makefile target generation performance

README.md, runners/slang
This adds a simple driver for [slang](https://github.com/MikePopoloski/slang)
This assumes that slang SystemVerilog compiler `driver` is located in `PATH`
=> runners: add simple slang runner

conf/report-template.html
There is no need to force the log overlay to occupy 60% of the screen
when there is little to be displayed.
For example:
(in this case the tool shows no logs, as it doesn't by default if it succeeded)
=> report: allow the log overlay to be smaller

conf/report-template.html, tools/sv-report
Instead of concatenating the logs for all test-cases, create tabs to allow viewers to switch between logs of individual tests.
This allows users to quickly find the test that actually failed.
For example:
Next step:
Make the cells which contain both successful and unsuccessful test distinguishable - e.g. make them yellow/orange.
Note: this PR also induces a commit with some PEP8 fixes for the report generator script.
=> Tabs for logfiles

tools/sv-report
Using some jinja parameters to do that. Thanks to this change the generated report has half the lines it had before.
=> report: trim redundant whitespace in the generated file

conf/report-template.html, tools/sv-report
If one feature is tested by more than one test and the results of the tests vary, it should be clearly visible in the report.
This PR marks such features with orange.
Depends on #14 (and includes patches from there), feel free to comment but do not merge yet.
=> explicitly mark features with varied results

conf/report-template.html
Highlighting the currently selected cell makes it easier to see what do
the currently displayed logs refer to.
The cell is highlighted with a solid, thick border:
=> highlight the currently selected cell

Makefile, tools/runner, tools/sv-report
When there are many results and test cases it is better to see some more output. Otherwise it may seem that the process just gets stuck.
Output after the patches from this PR:
```
$ make -j13
Found the following runners:
* icarus
* verilator
* odin
* slang
* yosys
* fake
Found the following tests:
* counter.sv
* always.sv
* typedef.sv
* sanity.sv
INFO    | Running icarus/counter.sv
INFO    | Running verilator/always.sv
INFO    | Running verilator/typedef.sv
INFO    | Running icarus/always.sv
INFO    | Running icarus/sanity.sv
INFO    | Running icarus/typedef.sv
INFO    | Running odin/counter.sv
INFO    | Running verilator/sanity.sv
INFO    | Running odin/sanity.sv
INFO    | Running odin/typedef.sv
WARNING | FAIL: icarus/counter.sv
WARNING | FAIL: odin/counter.sv
INFO    | PASS: …
```
=> Make the makefile output more verbose

tools/runner, tools/sv-report
Change to /usr/bin location as it is more popular across different Linux distributions. Also it fixes execution errors when running on Ubuntu 18.04.2.
=> tools: Change env binary location to /usr/bin

runners/yosys
There is lots of tests and including the banners in each log for yosys is pointless and makes the logs much less readable.
=> Hide yosys banners

runners/verilator
Warnings should be accepted for syntax-checking tests.
The list warnings that verilator fails on without this flag include:
* implicit type conversions
* multiple top modules
So situations that are perfectly valid in terms of syntax.
=> verilator: don't fail because of warnings

tools/runner
When test was marked as `:should_fail: 0` it would show in logs as failed
regardless of return code due to error in return code comparison
=> tools: fix issue with tests erroneously being logged as failed

conf/report-template.html
When hovering the tag in the report table the description from the
database will appear in a tooltip.
For example:
Closes #29
=> Add names to the tags in the report

conf/report-template.html, tools/sv-report
Show how many tests are there for individual features and how many of those passed for particular tools.
Note that the screenshot shows tests from #21 
A nice side-effect of this is being able search for `/` to display only the features with any tests.
=> Show more details in the report cells

conf/report-template.html
The tabs in the report looked good when there are just a few tests:
However when there are lots and lots of tests (Tested with tests from #21), they are pretty much unusable:
This PR addressees this issue by:
* making the tabs smaller (both in terms of font and padding)
* making the tabs fixed size (arbitrarily chosen 8 tabs per line - this could be adjusted)
* adding a scrollbar to when there is lots of tabs
* changing the method the selected window is highlighted - previously the tab was _merged_ with the log window - it looked pretty and cool if there was just one row of tabs, but this just doesn't scale to multiple rows. Right now the selected tab gets a thicker border and a bold font.
* allowing the log window to occupy more space that was allowed earlier
* trimming the name on the …
=> Improve the log file tabs in the report

Makefile, conf/report-template.html, tools/sv-report
The currently open WIP PRs show that the number of tests will be
significant. Therefore a better organization is needed.
This patch allows the tests to be put in subdirectories. This is a first
step towards a better organization of the files.
=> Allow the tests to be in subdirectories

Makefile, tools/runners.mk
After adding the short names in 3c00f2b4a1ba, executing the 'runners' target always forced a rebuild of each runner. Fix the dependencies so that the tools are not rebuilt if the binary already exists.
This PR adds several Makefile target fixes, including the dependencies, a minor variable usage bug and marking the targets as PHONY where relevant.
=> Makefile: fix dependencies between runner targets

Makefile
Originally the suite was designed in a way to rerun everything every
time on purpose, but as there is much more tests now, it makes more
sense to only rerun the test that actually changed. Otherwise we waste development time.
=> Do not rerun tests that did not change

conf/report-template.html
This makes the header of the table stay on top of the page when
scrolling down.
Ref: https://datatables.net/extensions/fixedheader/
=> enable the fixed header extension

tools/runner, tools/sv-report
Use the exit codes to determine that.
Exit codes 126 and above are generally considered "abnormal" exit codes.
Use that convention here.
Ref: http://tldp.org/LDP/abs/html/exitcodes.html
Fixes #32.
=> Differentiate between "should fail" and "tool broken"

.gitmodules, Makefile, generators/swerv, tools/runners.mk
As mentioned in #68, SymbiFlow uses `third_party` directory for adding this kind of submodules and we probably should do the same
=> Move third-party submodules to third_party directory

.gitmodules, conf/lrm.conf, generators/ibex
This adds Ibex core as a test with its separate tag `ibex`
Closes #59 
Depends #68 
Depends #70
=> Add Ibex as a test

tests/chapter-8/8.26.6.3--diamond_relationship_parametrized.sv, tests/chapter-8/8.5--parameters.sv
- 8.26.6.3: diamond relationship will fail, but for the
wrong reasons.
- 8.5: parameter to class given with $ instead of #
=> Fix a couple of smallish typos in tests.

Makefile, tools/runner
Currently `tools/runner` was configured for `DEBUG` logging level but as suggested in #81 it should be reduced
Closes #81
=> Reduce runner console log verbosity

conf/report-template.html
This adds column with tag description to the report page
Closes #84
Closes #75
=> Add tag description to report page and left align tag name

tests/chapter-5/5.10-structures.sv
Wrong assignment_pattern form when using "default" 
No semi-column allowed after begin or end keywords
=> Wrong assignment_pattern form when using "default"

tools/sv-report
Currently all tags must be defined in `lrm.conf` file, with this adding entry there is only required to change the tag description from the default empty one.
Additionally any tags without tests are omitted from the report.
Closes #85
=> Add support for dynamic tag discovery

.travis.yml, Makefile, tools/BaseRunner.py, tools/check-runners, tools/runners/Icarus.py, tools/runners/Odin.py, tools/runners/Slang.py, tools/runners/Sv2v_zachjs.py, tools/runners/Verilator.py, tools/runners/Yosys.py, tools/runners/tree_sitter_verilog.py
Currently all tools are used without checking if a particular tool is installed, in #83 it was suggested to test if tools are present before using them and this adds support for checking that.
If tool is not present then testing it will be skipped and it won't be included in the report.
Closes #83
=> Check if tool is installed before using it

conf/report/report.css
The fixed 10px font is hardly readable on high-res screens. Without
fixing the size, we can have the browser choose the best-looking
version.
=> Let the browser decide best font-size for report cells.

Makefile, conf/requirements.txt, tools/formatter, tools/sv-report
This fixes #162 and adds syntax highlighting using [pygments](http://pygments.org/).
Syntax highlighted sources look like this:
=> report: add syntax highlighting

.gitignore
These seem to appear in several places when generating the report.
=> Add __pycache__ dirs to gitignore

conf/report/report.css, conf/report/report.js
Make the currently selected cell highlighted.
This was already implemented earlier, but seems to have been removed by accident in #117.
Some style adjustments were needed to make it work/look good after changes in #163
Example of a selected cell:
=> report: restore current cell highlighting

tests/chapter-6/6.9.2--vector_scalared.sv, tests/chapter-6/6.9.2--vector_vectored.sv
=> 'vectored' does not apply to type 'logic'

tools/runners/Icarus.py
This should make it pass several tests according to: #138 
Depends on #193 (to pull in the latest changes regarding the `-i` switch).
=> runners: add the -i switch to icarus invocation

conf/report/report-template.html, conf/report/report.js, tools/sv-report
Look for the very first file in the `files` parameter in the tests, and open it in the designated pane after opening the tab.
=> Automatically open the first file from the log

Makefile, conf/report/code-template.html, conf/report/code.css, tools/sv-report
This is a PR to allow us to apply custom css styles for pygments.
This is useful because:
* Allows us to use one css file for all files (at the moment each code listing includes its own copy of the css)
* Should make it easier to add support for line highlighting (when clicking on an error in a specific line in a log file)
How it looked before this PR (note the misaligned line numbers and code):
And now:
And note that this is still mostly a door for further improvements (which should be now easy with an external css).
=> Custom pygments styles

.gitmodules, conf/generators/meta-path/hdlconvertor.json, conf/lrm.conf
Depends on #117
Slang seems to have issues with those tests on my PC, it uses up all the available RAM and swap on some of the cases, for example `tests/sv_test/std2017/p550.sv`. I wonder how this will behave in travis CI.
=> Import tests from hdlConvertor

Makefile, conf/report/report-template.html, conf/report/report.css, tools/sv-report
This adds a small footer to the report with a link to the github repository and info about the commit from which the report has been generated.
It is useful because it is not always clear whether the report has been generated from the latest master (as the CI is often busy doing other stuff).
Here is a screenshot:
=> report: add a footer with git rev

.dependabot/config.yml
It creates too many PRs that we don't merge regularly anyway and creates
a lot of CI builds which block the CI builds for PRs that we actually
care about.
=> Run dependabot less frequently

tests/generic/number/number_test_63.sv
=> Numeric literals should not start with underscore (_)

tools/sv-report
The same source file can be mentioned multiple times, so make
sure to only generate it the first time.
(This speeds up sv-report 3x)
=> Avoid multiple generation of src-file HTML.

Makefile
Unless @echo, Makefile rules should never be silent so that
it is observable what the build-system is doing.
(Fixes #80)
=> Don't make generator running silent.

Makefile
This looks like a left-over from the early days, when the
tool-runners were still silent; now it just adds noise.
=> Don't run unrelated 'info'-target when generating the report.

tools/check-runners
Before, every invocation of 'make', which determines the
runners to generate rules, will output a confusing message
about the non-found runners (even if invoking targets that
don't even have to deal with it, e.g. generate-tests).
=> Make message about a non-found runner a debug-log.

conf/report/log-template.html, tools/BaseRunner.py, tools/runner, tools/runners/Icarus.py, tools/runners/Odin.py, tools/runners/Slang.py, tools/runners/Sv2v_zachjs.py, tools/runners/Verilator.py, tools/runners/Yosys.py, tools/runners/tree_sitter_verilog.py, tools/sv-report
Generate the logs using a template too.
Add a link to each tool in the log (fixes #76)
With this change, the log looks like this:
The name of the tool in the log is a link to the projects website.
Another change here is removing the short arguments for templates. There are multiple templates already, we may want to just move them to a separate directory and have an argument for all of them together, but for now, just change them to long arguments only,
=> Add a html template for the log files

tools/BaseRunner.py
There are versions of `slang` that keep allocating memory until
the test-machine gets in trouble. Limit memory for sub-processes.
=> Limit resources the runners can take to run.

Makefile
It appears that #243 by accident also disabled checks for missing tools which CI used.
This PR adds them back but this time outside of any target rule and with a more verbose error message.
=> makefile: add back checks for missing runners

tests/generic/preproc/preproc_test_10.sv, tests/generic/preproc/preproc_test_11.sv, tests/generic/preproc/preproc_test_12.sv, tests/generic/preproc/preproc_test_13.sv, tests/generic/preproc/preproc_test_9.sv
As pointed out in #239, LRM doesn't allow for line continuations in argument lists but states that arguments can be separated using whitespace and newline is counted as whitespace character by the LRM in `5.3`.
That means that multiline argument list without newline escaping should be all right.
Fixes #239
=> tests: fix issues with newline escaping in macro definitions

.travis.yml, Makefile
This adds `make format` target for pep8 checks and replaces check in CI with it
Fixes #261
=> makefile: ci: use make format for pep8 checks

conf/report/report-template.html, tools/sv-report
Implements algorithm suggested in #267.
A new copy with sorted test data has to be created as python dicts are not ordered.
Fixes #267
=> Sort test-case names within one tag

.style.yapf, .travis.yml, Makefile, conf/requirements.txt, generators/ibex, generators/path_generator, generators/swerv, generators/template_generator, tools/BaseRunner.py, tools/check-runners, tools/runner, tools/runners/tree_sitter_verilog.py, tools/sv-report
This PR modifies `make format` command to use `yapf` to automatically adjust python code formatting
and adjusts CI to check if the code is formatted properly.
Closes #261
=> Modify python format checks to use yapf

tests/chapter-6/6.18--typedef.sv
`typedef` must take `data_type`, but `wire` is `net_type`.
```
type_declaration ::= typedef data_type type_identifier { variable_dimension } ;
```
=> Fix data_type of typedef

tests/chapter-12/12.6.3--conditional_pattern.sv
`cond_predicate` of conditional expression can't include parenthesis.
```
conditional_expression ::= cond_predicate ? { attribute_instance } expression : expression
cond_predicate ::= expression_or_cond_pattern { &&& expression_or_cond_pattern }
expression_or_cond_pattern ::= expression | cond_pattern
cond_pattern ::= expression matches pattern
```
=> No parenthesis in conditional expression

generators/path_generator
Some tests (ex. utd-sv) seems to need incdirs to the same directory as the tests.
=> Add incdirs to path_generator

conf/report/report-template.html
Without this, the columns get generated in different order every time
the report is made.
=> Sort columns with the tools

tools/sv-report
The code and source templates were parsed every time they were used,
but we only need to do this once. On my machine, that brought an
reduced time of 60s -> 38s.
=> Some low-hanging performance fruit: parse templates only once.

conf/report/report.js
this takes care of the issues listed in #295 and fixes issues with URI decoding ie. `|` getting replaced with `%7C`
Fixes #295
=> report: fix minor issues in test url handling code

tools/runners/Sv2v_zachjs.py
It has been renamed from -i to -I and we're getting a deprecation
warning in the logs.
See: https://github.com/zachjs/sv2v/commit/c0e38f793d0677f91d363bf519e7c4fa65d2bd44
=> tools: sv2v: fix include directories flag

tools/runner
This PR adds support for includes in tests that were not generated.
With this it should be possible to specify incdirs as relative paths from repository root ie. `:incdirs: tests/generic/preproc`.
If `:incdirs:` is not specified, runners will now by default set it to directory containing the test.
Fixes #300
=> tests: support incdirs in non-generated tests

tools/sv-report
Parallelize looking for/reading/parsing log files.
This improves the report generation time (on my machine) from:
```
$ time make -j13                                                                                                                          
./tools/sv-report --revision 99d7d489d
INFO    | Generating out/report/index.html from log files in 'out/logs'
cp ./conf/report/*.css ./out//report/
cp ./conf/report/*.js ./out//report/
real    0m50.345s     
user    0m49.098s
sys     0m1.116s 
```
to:
```
$ time make -j13                                                                                                                          
./tools/sv-report --revision 99d7d489d …
```
=> Parallelize parsing log files

conf/report/code.css, conf/report/log-template.html, conf/report/report-template.html, conf/report/report.css, tools/sv-report
* Highlight the current grid-box more visibly with a thicker and blue box.
* Make the main-grid fill the width of the browser. Previously, it was only using the center, leaving a lot of whitespace around.
* Highlight the summary line with some gray background.
* Show the header of the logfile in green/red for faster visual parsing (moved status calculation before logfile html generation in sv-report for that; removed some older debug logs in the course of that)
=> Small UI tweaks.

conf/report/report-template.html
The column of "Total time elapsed" has the wrong order than other columns.
=> Fix order of "Total time elapsed"

.travis.yml, conf/environment.yml, conf/requirements.txt, tools/runners.mk, tools/runners/Slang.py, tools/runners/tree_sitter_verilog.py
This PR aims to replace current mix of locally built tools and system packages used in CI with packages downloaded from SymbiFlow conda [repository](https://anaconda.org/SymbiFlow/repo)
To achieve that, all tools we test should be available from that repo
Current tool status:
Closes #54
=> Use anaconda packages

tools/sv-report
Report generator seems to again require tags to be defined in `lrm.conf` before including them in the report file. This PR aims to fix that and to allow to use tags not defined in the configuration file.
=> report: don't omit tags missing from lrm.conf

Makefile, conf/report/report-template.html, conf/report/report.css, tools/BaseRunner.py, tools/runner, tools/runners/Icarus.py, tools/runners/Odin.py, tools/runners/Slang.py, tools/runners/Sv2v_zachjs.py, tools/runners/Yosys.py, tools/sv-report
This PR changes the structure of the runners. Instead of a single
script file, there are now directories with single script files.
The reason is that the directory will be used as the displayed name of
the runner (e.g. slang), but the script name will be used to determine
where does the actual tool binary come from (e.g. driver for slang).
This is needed to be able to find out whether the tool that is tested
comes from a submodule or is provided externally.
The tool is now versioned in two ways:
* using the appropriate `--version` switch for the tool
* if it comes from the submodule, using the commit hash from git
If any of the above is impossible `n/a` is shown instead of the version string/commit hash.
Because there is no standard `--version` switch for all the tools, the
runners as the …
=> Add information about the versions of the tools

conf/generators/meta-path/hdlconvertor.json
#129 added most of them, but tests located outside of `std2012` and `std2017` directories were omitted.
This aims to add tests from `sv_pp` and `verilog` which are preprocessor tests older verilog tests.
Closes #56
=> Add more tests from hdlConvertor

conf/generators/meta-path/utd-systemverilog.json
This PR add some files of utd-sv to blacklist.
* pad_jbusl.v,pad_jbusr.v : bw_io_dtl_padx12 has `ref` port. This is a keyword of SystemVerilog.
* fpu_in_ctl.v: parameter override like `dff_s #16` is invalid because parenthesis is required.
=> Add incorrect files of utd-sv to blacklist

conf/generators/meta-path/hdlconvertor.json
This PR add some files of hdlconv to blacklist.
* p12.sv: `* module mux2to1` is invalid.
* p940.sv: `import "DPI-C" \begin` is invalid because `\begin` is not c_identifier.
```
dpi_import_export ::= import dpi_spec_string [ dpi_function_import_property ] [ c_identifier = ] dpi_function_proto ;
c_identifier ::= [ a-zA-Z_ ] { [ a-zA-Z0-9_ ] }
```
=> Add some files of hdlconv to blacklist

conf/report/report-template.html, conf/report/report.js
Adjust the margin at the bottom of the page each time a log is
displayed.
This helps the situation when you are at the very bottom of the table and the log popup covers the table in a way that you are unable to switch for example to another tool.
With this change the whole table can be visible at all times.
Note that I also experimented with separating the page into two panels, but I thing the usability drops with that setup. It seems much more user friendly when the logs are in a modal window which can easily be closed (if you are interested in the overview report).
=> Make sure the whole report table is always visible

conf/report/log-template.html, conf/report/report-template.html, tools/sv-report
The data is now displayed in the html report:
- each test has it's individual memory usage listed in the pop-out window
- sum of user and kernel time and maximum ram usage is displayed at the bottom of the page, under respective simulator
=> Modified report generating script and html templates

conf/generators/templates/encapsulation.json, tests/chapter-11/11.4.14.3--unpack_stream_inv.sv, tests/chapter-11/11.9--tagged_union_member_access_inv.sv, tests/chapter-5/5.10-structure-arrays-illegal.sv, tests/chapter-6/6.12--real_bit_select.sv, tests/chapter-6/6.12--real_bit_select_idx.sv, tests/chapter-6/6.12--real_edge.sv, tests/chapter-6/6.19--enum_xx_inv.sv, tests/chapter-6/6.19--enum_xx_inv_order.sv, tests/chapter-6/6.19.3--enum_type_checking_inv.sv, tests/chapter-6/6.19.4--enum_numerical_expr_no_cast.sv, tests/chapter-6/6.20.5--specparam_inv.sv, tests/chapter-6/6.5--variable_mixed_assignments.sv, tests/chapter-6/6.5--variable_multiple_assignments.sv, tests/chapter-6/6.5--variable_redeclare.sv, tests/chapter-7/arrays/packed/variable-slice-zero.sv, tests/chapter-7/structures/packed/default-value.sv, tests/chapter-8/8.21--abstract_class_inst.sv, tests/chapter-8/8.25.1--parametrized_class_invalid_scope_resolution.sv, tests/chapter-8/8.26.3--type_access_implements_invalid.sv, tests/chapter-8/8.26.4--illegal_forward_def_implements.sv, tests/chapter-8/8.26.4--illegal_implements_parameter.sv, tests/chapter-8/8.26.5--invalid_interface_instantiation.sv, tests/chapter-8/8.26.6.1--name_conflict_unresolved.sv, tests/chapter-8/8.26.6.2--parameter_type_conflict_unresolved.sv, tests/chapter-8/8.26.6.3--diamond_relationship_parametrized.sv, tests/chapter-9/9.3.3--fork_return.sv
Some testcases having `:should_fail: 1` can't be passed by parser because it is semantic error.
=> Add simulator type to testcases for semantic error

Makefile
The `sed` distributed on macOS doesn't support the `I` flag. I believe this alternative should serve the intended purpose.
=> compatibility with BSD sed

tests/chapter-13/13.4.1--function-void-return.sv, tests/chapter-13/13.4.4--fork-invalid.sv
Some tests detecting semantic error should be `:type: simulation`.
=> Fix test type

conf/report/report-template.html, conf/report/report.css
These changes are obviously subjective. I'm eager to receive any feedback.
Before:
After: (local run with fewer tools set up)
=> Reduce visual noise in the footer

conf/generators/meta-path/hdlconvertor.json
* p137.sv
`randomize_call` takes `variable_identifier_list`. So hierarchical identifier like `p.address` is forbidden.
```
randomize_call ::=
randomize { attribute_instance }
[ ( [ variable_identifier_list | null ] ) ]
[ with [ ( [ identifier_list ] ) ] constraint_block ]
```
* p552.sv
The return type of function can't take `int[$]` because `data_type` can't take `queue_dimension`.
```
function_data_type_or_implicit ::=
data_type_or_void
| implicit_data_type
```
```
data_type ::=
integer_vector_type [ signing ] { packed_dimension }
| integer_atom_type [ signing ]
| non_integer_type
| struct_union [ packed [ signing ] ] { struct_union_member { struct_union_member } }
{ packed_dimension }
| enum [ enum_base_type ] { enum_name_declaration { , enum_name_declaration } }
{ packed_dimension }
| …
```
=> Add some tests of hdlconvertor to blacklist

tests/chapter-22/22.7--timescale-basic-3.sv, tests/chapter-22/22.7--timescale-basic-4.sv
I think unit/precision check of timescale is semantic error.
=> Change type of timescale error case

generators/uvm
uvm seems to take a long time. In my environment, sv-parser took about 15s.
=> Increase uvm timeout

tests/chapter-16/16.2--assert.sv, tests/chapter-16/16.2--assume.sv, tests/chapter-16/16.2--cover.sv
simple_immediate_assertion_statement can't directly put under module declaration.
=> Fix procedural assertion

tests/chapter-7/arrays/associative/methods/traversal.sv, tests/generic/number/number_test_63.sv, tests/generic/typedef/typedef_test_22.sv
number_test_63: Leading underscore in spec means before anything.
typedef_test_22: Fix to properly check for fwd decls.
associative/methods/traversal: Fix to avoid type mismatches.
=> Fix some minor test issues

tools/logparser.py, tools/runners/Verilator.py
=> Fix Verilator vmodel not found errors, bug438.

tests/generic/number/number_test_63.sv
`_23_` is an invalid number but a valid identifier, so this test should be passed.
To check `_23_` as number, `time_literal` can be used because it can't take identifier.
=> Fix number_test_63

conf/generators/meta-path/basejump.json, generators/path_generator
This is some fixes for basejump.
* Add `commons` to path_generator
basejump uses many defines at `cores/basejump_stl/bsg_misc/bsg_defines.v`.
The files in `commons` section are added to `:files:` by path_generator.
* Add `incdirs` to path_generator
basejump expects some include directory like `cores/basejump_stl/bsg_misc`.
The directories in `incdirs` section are added to `:incdirs:` by path_generator.
* Add some testcases to blacklist
* test_bsg_clock_params.v
`initial` can't be at top-level.
* bsg_nonsynth_mixin_motherboard.v
`` `BSG_NONSYNTH_MOTHERBOARD_MIXIN_module_name`` is not defined anywhere.
* bsg_1_to_n_tagged_fifo_shared.v
`` `BSG_SAFE_CLOG2(buffering_p)`` in ``logic [num_out_p-1:0][`BSG_SAFE_CLOG2(buffering_p)] els;`` is not range.
* bsg_fifo_1r1w_large_banked.v, …
=> Fix error at basejump

conf/runners/vmain.cpp, tests/chapter-11/11.4.13--set_member.sv, tests/chapter-20/20.5--shortreal-bits-conv.sv, tests/chapter-22/22.10--celldefine-invalid.sv, tests/chapter-22/22.5.1--include-define-expansion.sv, tests/chapter-22/dummy_include.sv, tests/chapter-22/include_directory/defs.sv, tests/chapter-24/24.3--program.sv
This fixes the following test problems:
11.4.13--set_member: test standard usage
20.5--shortreal-bits-conv: Fix to account for rounding.
21.6--test ($test$plusargs) requires argv
22.5.1--include-define-expansion etc has no module; is preproc only.
24.3--program.sv to be legal.
Remove 22.10--celldefine-invalid. IEEE does not specifiy celldefine is alone on line or not, hence legal if foo is passed through and passes.
=> Misc test fixes

tools/runners.mk
Building all runners in parallel is pretty noisy as all of them
try to do some smart terminal line-rewrite to show some sort
of percentage, but when they compile all in parallel it is pretty
messy.
=> Make verible build less noisy.

conf/generators/meta-path/basejump.json, generators/path_generator
bsg_scatter_gather.v is too large ( about 1.7MB ).
So this PR increases the timeout from 10s to 60s.
=> Add timeout to path_generator

tests/chapter-9/9.4.2.1--event_comma_op.sv, tests/chapter-9/9.4.2.1--event_or_op.sv, tests/chapter-9/9.4.2.2--event_implicit.sv, tests/chapter-9/9.4.2.3--event_conditional.sv, tests/generic/number/number_test_63.sv
9.4.2.1--event_comma_op, etc: Fix illegal procedural assignment to wire.
generic/number/number_test_63: Remove, not testing what was intended.
=> Test fixes3

conf/generators/meta-path/yosys-asicworld.json, conf/generators/meta-path/yosys-errors.json, conf/generators/meta-path/yosys-simple.json
This PR adds some testcases of yosys to blacklist.
* code_verilog_tutorial_counter_tb.v, code_hdl_models_arbiter_tb.v, code_verilog_tutorial_first_counter_tb.v, code_verilog_tutorial_fsm_full_tb.v
These include an undefined macro `outfile`.
* hierdefparam.v
`generate` block can't take `begin/end` directly.
* memory.v
`bit` is a reserved keyword.
* syntax_err06.v, syntax_err09.v, syntax_err13.v
These seem to be semantic error.
* syntax_err12.v
This may be semantic error.
`iface` can be user-defined type or interface syntactically.
If `iface` is used-defined type, the assignment is valid.
=> Add some testcases of yosys to blacklist

tools/runners/Verilator.py
1. Use pedantic flags with Verilator so it avoids some good-user behavior for strict compliance.
2. Fix harness bug which was not crediting verilator for correct fails.
=> Verilator correct fails and pedantic tests

tools/runner, tools/sv-report
Not all tests are run, e.g. tests for simulation are not
run by runners that only can do preprocessing.
Previously, these tests didn't generate any logfiles, so were
considered by the Makefile to re-run every time as the Makefile
considers the logfile as output. As a result, make never
considered the output as 'complete'.
Fix this by creating an empty logfile in that case and properly
skip these in the report generation.
=> Don't run tests that are disabled every time.

tests/generic/typedef/typedef_test_10.sv, tests/generic/typedef/typedef_test_11.sv, tests/generic/typedef/typedef_test_12.sv, tests/generic/typedef/typedef_test_13.sv, tests/generic/typedef/typedef_test_14.sv, tests/generic/typedef/typedef_test_18.sv, tests/generic/typedef/typedef_test_9.sv
Declares types before use as required by IEEE.
=> Fix typedef_test_9 etc: Declare types before use as required by IEEE.

.github/kokoro/continuous.cfg, .github/kokoro/run.sh, .github/kokoro/steps/hostsetup.sh
Run all tests on Kokoro and then publish the results onto the `gh-pages` branch using
the SSH key pair stored in the Kokoro keystore.
=> kokoro: Push the sv-tests report result to GitHub.

conf/generators/meta-path/basejump.json
This PR fixes #381 .
I think there are two files which should be blacklisted.
* bsg_nonsynth_mixin_motherboard.v
This file requires `BSG_NONSYNTH_MIXIN_MOTHERBOARD*` defines.
* test_bsg_clock_params.v
This file is included from other files, and the single file can't be parsed.
=> Remove basejump blacklist

.gitmodules, conf/lrm.conf, generators/ivtest, tools/BaseRunner.py
This adds generator that imports most of the tests in `ivtest`
In it's current form it has several issues:
- It imports most of the tests but some should be omitted(VHDL integration, `Verilog-AMS`)
- Our `Makefile` can't handle that much tests in the `info` target and `@echo -e "Found the following tests:$(subst $(space),"\\n \* ", $(TESTS))\n"` had to be removed
- It makes the report page substantially slower, ie. switching between results of individual tests takes seconds
- `report.html` gets as big as 40MB which is too big to serve as a single static webpage and probably we should somehow load the results in a more dynamic way or at least store the logs in separate files
Closes #57 
Updated version depends on #117
=> Import tests from ivtest

conf/report/report-template.html, tools/sv-report
Currently the denominator of total tags includes tags which has no test.
This PR change the denominator to the count of tested tags.
=> Fix total tags

conf/runners/vmain.cpp
Fixes an issue in the test harness which was false failing any test on verilator using $time indirectly e.g.  20.10--info.sv
=> Fix Verilator driver to not false-fail when $time used

tests/chapter-5/5.9-string-word-assignment.sv
IEEE says assignment to *packed* or a unpacked array of bytes is legal, not an *unpacked* bit array.
=> 5.9-string-word-assignment: Fix single-bit assignment.

conf/generators/meta-path/basejump.json
I fixed some testcases in basejump_stl.
* define in bsg_cache_non_blocking_pkg.v is used in some testcases.
* module instance name is missing: bsg_sbox_ctrl_concentrate.v, bsg_stable_sort.v
* wrong associative array assignment: bsg_cache_non_blocking_mhu.sv
=> Fix basejump_stl

generators/ivtest
This PR fixes some testcases in ivtest.
* Added `:incdirs:`
* Added `:type: simulation` because testtype `CE` and `CO` show not syntax error but semantic error
* Remove `EF` and `TE` from `type_shoud_fail` because they should be failed only by icarus
* Added entries of `ivtest_blacklist`
=> Fix ivtest

tests/chapter-20/20.10--error.sv, tests/chapter-20/20.10--fatal.sv, tests/chapter-20/20.10--warning.sv
Once pull #592 is applied, Verilator is false-failed out on
* tests/chapter-20/20.10--error.sv
* tests/chapter-20/20.10--fatal.sv
* tests/chapter-20/20.10--warning.sv
because these tests are themselves creating errors.  Likewise Icarus is false-failed on $error.  The various parsers consider everything fine.  The difference is in policies on what returns bad exit status.
This pull makes them non-simulator tests, as this seemed the best route to have them indeterminate.
The $info test remains simulation, as never should fail.
=> Fix $error/fatal/warning to be non-simulator.

conf/generators/templates/encapsulation.json
This PR fixes the issue with not generating logs for encapsulation tests mentioned in #437 
It appears that wrong column was used for `:type:` field
=> conf: fix encapsulation test template

Makefile, tools/runner
As suggested in #445 this adds option to keep the directories in `/tmp` by setting `RUNNER_KEEP_TMP` variable
=> tools/runner: add option to keep runner work directory

conf/generators/meta-path/basejump.json
This PR fixes commons of basejump.
In the current master branch of basejump, `bsg_fpu_pkg.v` is not used.
=> Fix basejump commons

tests/chapter-7/arrays/packed/slice-equality.sv, tests/chapter-8/8.10--static_methods.sv, tests/chapter-8/8.13--inheritance.sv, tests/chapter-8/8.14--override_member.sv, tests/chapter-8/8.15--super.sv, tests/chapter-8/8.23--scope_resolution.sv
Fix some tests.
* slice-equality: Fix wrong expectation.
* chapter-8: These tests should mostly test the feature they describe and not fail if assignment-within-expression is unsupported, for which there is already a separate test.
=> Tests: Fix slice-equality and assignment expectations

generators/ivtest
This PR fixes https://github.com/SymbiFlow/sv-tests/issues/577.
=> Add undef.v of ivtest to blacklist

tests/chapter-5/5.6.1--nonescaped-access.sv
Not exactly sure if the following is correct, and also if the test makes sense.
Therefore, it would be nice the get feedback from people who are more experienced with the spec.
Following the description of Chapter 5.6.1 the backslash or following
white space is not part of the identifier.
As an example the escaped identifier `\cpu3` is the same as the
nonescaped identifier `cpu3`.
Add an escaped identifier and use it nonescaped.
Escalate the undefined usage to an error.
=> Add equality check for escaped identifiers

conf/report/report-template.html, tools/sv-report
This PR add "Average throughput passed" column.
Now the comparison of performance by "Total time elapsed" is difficult because there are many variation about pass/fail, size of test-case and type of test-case.
I think average throughout of passed test-cases may be better comparison.
=> Add "Average throughput passed" column

conf/report/report-template.html, tools/sv-report
The throughput calculation makes more sense for files that are more
than just a few lines (like many of the LRM tests), so only include
tests in the throughput calculation that are at least 1KiB.
In the output, round the calculated throughput to full kibibytes/s; the
double-digit post-decimal point resolution is more accurate than
noise will allow.
=> Only calculate throughput for larger tests.

tests/chapter-12/12.4--if.sv, tests/chapter-12/12.4--if_else.sv, tests/chapter-12/12.4.1--if_else_if.sv, tests/chapter-12/12.4.2--priority_if.sv, tests/chapter-12/12.4.2--unique0_if.sv, tests/chapter-12/12.4.2--unique_if.sv, tests/chapter-12/12.5--case.sv, tests/chapter-12/12.5.1--casex.sv, tests/chapter-12/12.5.1--casez.sv, tests/chapter-12/12.5.2--case_const.sv, tests/chapter-12/12.5.4--case_set.sv
As pointed out in #138 some `always` blocks were infinite loops, this PR aims to fix those cases
=> tests: fix always block to use sensitivity lists

tools/runners/Surelog.py
The Python-API is somewhat expensive to initialize. This reduces
the overall runtime of Surelog parsing by a few hundred seconds.
=> Disable Python feature when invoking surelog.

generators/ariane, generators/earlgrey, tools/BaseRunner.py
Also: Print what the actual timeout was in the log.
=> For some larger tests: give a little more timeout-slack to slow tools.

conf/report/log-template.html, tools/BaseRunner.py, tools/runner, tools/runners/Surelog.py, tools/sv-report
was successful. Use for filtering Surelog return codes.
Fixes #663
=> Provide a runner function that returns if a tool return code

tests/chapter-22/22.4--include_basic.sv, tests/chapter-22/22.4--include_with_comment.sv, tests/chapter-6/6.19--enum_value_inv.sv, tests/generic/enum/enum_test_0.sv, tests/generic/struct/struct_test_0.sv, tests/generic/typedef/typedef_test_0.sv, tests/generic/typedef/typedef_test_19.sv, tests/generic/typedef/typedef_test_22.sv, tests/generic/typedef/typedef_test_26.sv, tests/generic/typedef/typedef_test_27.sv, tests/generic/typedef/typedef_test_28__bad.sv, tests/generic/union/union_test_0.sv
Things being fixed here:
* The spec says angle bracket includes only search for files provided by the language implementation, not the user's directories or the compiler's working directory.
* The spec says forward typedefs must resolve to a type within the same scope. 
* The spec says enum value initializers that use sized constants must match the size of the enum's base type.
In addition to fixing the existing tests, I added some additional coverage to catch the invalid cases mentioned above.
=> Various test fixes

tools/runners/Slang.py
slang supports full elaboration, no need to restrict to just parsing and preprocessing.
When running in preprocessing mode, where tests don't expect to be fully compilable, use the -E flag to only preprocess.
=> slang runner: Set correct flag for preprocessing mode, use simple compilation unit mode

conf/report/log-template.html, tools/runner, tools/sv-report
Add should_fail_because functionality solving issue #449 
specs as per the issue :
- if should_fail and should_fail_because doesn't exist, it's automatically assume should_fail: 0
- if both exist and should_fail:0, then it exits because there is a contradictory should_fail: 0 tag and also a should_fail_because: <msg> tag
* I made it backward compatible till all the tests move to the new tag, so if should_fail_because doesn't exist it'll use should_fail as before
=> support should_fail_because tag

tools/runners/moore.py, tools/runners/moore_parse.py
Since the moore SV parser can be used as a standalone library, add a separate runner that just runs the moore parser, instead of also performing elaboration and code generation.
=> Add separate moore parser runner

tools/runners/Verilator.py
The Verilator version isn't in the report header, this should fix this since Version 4.026 fixed the problem with shebang that originally required this code.
=> Fix Verilator version report

tools/runners/moore_parse.py
Rather than emitting the entire parsed AST via `--dump-ast`, use the `--syntax` flag in the parse-only test of moore.
=> moore: Use --syntax flag for parsing

tests/chapter-6/6.20.2.1--parameter_unbounded.sv
Fixes backward array order. Thanks.
=> Fix chapter-6/6.20.2.1--parameter_unbounded.sv array ordering.

generators/ivtest
This disables some of the ivtests which can only pass on Icarus because they use Icarus-only extensions.
=> Tests: Turn off some ivtests which are Icarus only.

tests/chapter-7/queues/persistence.sv, tests/chapter-7/queues/pop_back_assing.sv
* tests/chapter-7/queues/persistence.sv - use methods as better supported
(Other tests check the old syntax so no new hole)
* tests/chapter-7/queues/pop_back_assing.sv - fix incorrect value
=> Queue test fixes.

tests/generic/class/class_test_55.sv, tests/generic/class/class_test_56.sv, tests/generic/class/class_test_57.sv, tests/generic/class/class_test_58.sv, tests/generic/class/class_test_6.sv
This fixes some of the class_tests to be legal.  More work is needed on other tests later - parameters, packages and classes all need to be declared before use.
=> Fix some class_tests to be legal code.

tools/runners/Icarus.py
Fixes #732
It seems that Icarus was never properly tested when simulation testing was added. It changed the invoked binary a different one (iverilog -> vpp) but kept the old switches.
This PRs makes iverilog only be tested as a parser to be more fair to it. I will open a new issue to add proper simulation testing for it shortly.
=> Test iverlog in parsing mode only

tests/chapter-22/22.9--unconnected_drive-invalid-1.sv, tests/chapter-22/22.9--unconnected_drive-invalid-2.sv, tests/chapter-22/22.9--unconnected_drive-invalid-3.sv
It's questionable where (if at all) these illegal tests would be implemented, but Verilator selected to implement them post-simulation.  I don't see any other tool that would now fail because of changing this, so I'd like Verilator to be able to get it's "green box", thanks.
=> Allow unconnected drive errors detected in simulation.

generators/black-parrot
Trying to fix the Verilator tests, which BlackParrot is known to support
=> Adding top-module to BlackParrot builds

Makefile, tools/BaseRunner.py
Thanks to this we can easily disable test timeouts with:
```
$ DISABLE_TEST_TIMEOUTS=1 make
```
This is useful for development.
=> Add an option to disable test timeouts

Makefile, tools/BaseRunner.py
This is similar to #848 but allows to keep the timeouts but set them to
a specific (very large or very small) value in bulk.
For example
```
$ OVERRIDE_TEST_TIMEOUTS=180  make
```
=> Allow overriding test timeouts in bulk

Makefile, tools/check-runners, tools/runner
Thanks to these changes we can use out-of-tree runners like this:
```
RUNNERS_DIR=/my/custom/runners/ make
```
It was always the intention to be able to do this but somewhere along the way we've lost that possibility. This PR just restores this.
=> Allow out of tree runners

tools/runner
This PR modifies `tools/runner` to always add library files/incdirs before the ones defined by the test itself.
This should help with #853
=> tools/runner: add library files before test files

tools/BaseRunner.py
Some runners seem to throw non utf-8 characters in their log for some
specific tests. Ignore the invalid characters to allow the test suite to
continue.
=> Fix runners logs decoding

tests/chapter-9/9.4.1--delay_control-sim.sv, tests/chapter-9/9.4.1--delay_control-two-blocks-sim.sv
Just test whether the time passed is right. Adding two tests as this is something that is known not to fully work in current verilator dev branch.
=> Add simulation tests for delay statements

generators/ariane, generators/earlgrey
On the CI machines, it is a hit-and-miss if they finish with Surelog
=> Allow for more timeout for Ariane and Earlgray.

tools/runners/UhdmVerilator.py
It is not available in uhdm-verilator (multiple tests fail because of
this flag).
=> uhdm-verilator: remove -Wpedantic flag

conf/generators/meta-path/basejump.json, conf/generators/meta-path/hdlconvertor.json, conf/generators/meta-path/utd-systemverilog.json, conf/generators/meta-path/yosys-asicworld.json, conf/generators/meta-path/yosys-errors.json, conf/generators/meta-path/yosys-memories.json, conf/generators/meta-path/yosys-simple.json, conf/generators/meta-path/yosys-sva.json, conf/generators/meta-path/yosys-svinterfaces.json, conf/report/log-template.html, generators/ivtest, generators/path_generator
This is related to https://github.com/SymbiFlow/sv-tests/issues/449
This PR does following things:
- remove all "should_fail: 0" statements because they are not needed (tests are assumed non-failing by default)
- change "should_fail: 1" tests to "should_fail_because" and add human-readable explanation
=> Migrate all remaining "should_fail" statements to "should_fail_because"

tools/sv-report
When source file is missing the program should continue
but log this information to output file.
This solves: https://github.com/SymbiFlow/sv-tests/issues/763
=> tools/sv-report: handle missing source files

Makefile, generators/black-parrot
* When run with cgroups, provide a little more memory to
run the runners (3GiB vs ~2GiB). Can now also be set by
CGROUP_MAX_MEMORY variable.
* Use the USE_CGROUP variable everywhere (some places still
used a hard-coded value)
* Make sure the memory limit is initialized even if the
cgroup already exists: this allows to experiment with
different memory settings with each run.
* don't create $(1)-cg: target twice (else/endif was missing)
* Somewhat independent, but while at it: provide a little longer
timeout to black-parrot.
=> cgroups: Provide more default memory.

.github/kokoro/run.sh
We're running with -j1, so only one test at at time is running
anyway.
=> Run Kokoro tests without cgroups.

conf/report/report-template.html, conf/report/report.css, tools/sv-report
For all test categories that comprise of a bunch of tests,
we currently show 'yellow' if they only pass partially.
Given that there are some of these where there are hundreds
or even thousands of tests lumped together, this is a very
coarse grained representation.
Changed this to a bargraph representation: now the percentage
of the box that represents passing tests is green, the rest
red.
We're loosing a happy yellow color in the output, but gaining
much easier insight of fraactions on tests on first sight.
=> Show bargraph for partially passing tests.

conf/report/log-template.html
We don't want empty should_fail_because in logs
Related to https://github.com/SymbiFlow/sv-tests/issues/915
Signed-off-by: Tomasz Jurtsch <tjurtsch@antmicro.com>
=> conf/report/log-template: make should_fail_because conditional

conf/report/report-template.html, conf/report/report.css
... with a slightly nasty calculation directly in the template.
=> Use bargraph representation also in summary line.

README.md
=> Add missing `-r` to pip install call.

conf/report/report-template.html, conf/report/report.css
Also: move logfile divs to the bottom of the page to hopefully
improve incremental loading experience.
Fixes #930 #931
=> Report-Page: Add a headline with link back to sv-tests.

tools/BaseRunner.py, tools/sv-report
Previous CSV file had one column per tool and in each of these only the
outcome of the test: True or False.
Now, have one row per (test, tool) tuple and output more relevant
information.
* `TestName`, `Tool`  *the selector*
* `Pass`  *{True or False}*
* `Tags`  *associated tags with the TestName; space separated*
* `InputBytes` *Bytes the input (System)Verilog files add up to*
* `ExitCode` *Exit code of the tool. Special value 71 for timeout (`71meout` :))*
* `AllowedTimeout`  *Timeout allowed for this test*
* `TimeUser`, `TimeSystem`, `TimeWall`
* `RamUsageMiB`
We are not emitting all associated filenames anymore per test - this was partially
a huge list for some of the tests, and not terribly useful. The TestName is unique.
Also: file content of report.csv changed, so someone who was …
=> Normalize CSV output and emit relevant data for each (test, tool) tuple.

.editorconfig
Editorconfig is understood by a large set of editors.
=> Add editorconfig <https://editorconfig.org/> to ease contribution.

tools/runners/moore_parse.py
`moore_parse` runner did not use `params['incdirs'] and cause false-negative failures on tests that do include other files.
This PR adds the necessary arguments just like used on `moore` runner.
=> moore: add incdirs to moore_parse

README.md
Use `$` consistently before all shell commands.
=> README: Normalize shell snippets

tests/chapter-6/6.20.4--localparam.sv, tests/chapter-6/6.20.4--localparam_int.sv, tests/chapter-6/6.20.4--localparam_logic.sv, tests/chapter-6/6.20.4--localparam_string.sv, tests/chapter-6/6.20.4--localparam_unsigned_int.sv
Looks like some tools are limited in types they accept for localparam. Add explicit tests for a few common types: int, int unsigned, logic and string.
=> Add typed localparam

tools/runners/YosysSv.py
The origin of the fork is not important from the perspective of
sv-tests.
Rename it to yosys-sv to make it clear that this is a yosys fork capable
of processing more SystemVerilog features and to make its column appear
right next to vanilla yosys.
=> Rename antmicro-yosys to yosys-sv

conf/report/report.js
Sort by the percentage of tests passed.
Fixes #972
Expect it to look more or less like this (except this was tested for a single runner):
=> Improve test results sorting

conf/report/report.js
The sorting mechanism introduced in #986 was broken for cells without any tests (the gray cells). They would remain in place and would not be affected by sorting.
This PR fixes it.
=> Fix sorting for cells without any tests

Makefile, conf/report/report-template.html, conf/report/report.css, tools/BaseRunner.py, tools/runner, tools/sv-report
The effect is similar to #997, but this is for the tool headers:
The columns can still be sorted by clicking on the order arrows (or anywhere in the cell except the text).
Fixes #957
=> Make tool names in the headers clickable

tests/generic/class/class_test_12.sv, tests/generic/class/class_test_13.sv, tests/generic/class/class_test_19.sv, tests/generic/class/class_test_21.sv, tests/generic/class/class_test_36.sv, tests/generic/class/class_test_37.sv, tests/generic/class/class_test_52.sv, tests/generic/class/class_test_8.sv
This fixes some class tests that are not legal because they do not predeclare referenced classes.
Also class_test_36.sv and class_test_37.sv are removed, IEEE does not allow import directly into classes.
=> class_tests: Fix missing predeclarations, etc

tests/chapter-9/9.3.4--block_names_par.sv, tests/chapter-9/9.3.5--statement_labels_par.sv
This modifies these tests to pass on Verilator (which doesn't support multiple parallel fork statements), but still checks what they are intended to test which is the block naming.   Many other tests still check the more complicated fork behavior.
Thanks
=> 9.3.4--block_names_par etc: Only check one Variable to appease Verilator

tests/chapter-5/5.6.4--compiler-directives-preprocessor-macro_0.sv
=> The :defines: test should test preprocessors

generators/fusesoc
There is a convention saying that we should parse the _pkg.sv files
before the rest of the .sv files. Ibex uses that convention.
CC: @kamilrakoczy
=> fusesoc: properly order the source files

tools/runners/UhdmVerilator.py
Simply feeding UHDM to Verilator allows us to see if we handle specific
types of nodes, so the Verilator-UHDM integration should run all types
of tests.
Fixes #1069
=> Make verilator-uhdm run all types of tests

tools/runners/Verible.py
Switch to using the current in-use name rather than the deprecated one.
This should remove the warning:
```
*******************************************************************************
verilog_syntax is the deprecated name for verible-verilog-syntax.
executing /home/kbuilder/miniconda/envs/sv-test-env/bin/verible-verilog-syntax instead
*******************************************************************************
```
=> Update verible linter command name

conf/generators/meta-path/yosys-simple.json
This blacklists a yosys test with illegal numbers.
=> Blacklist yosys values.v which has too many digits to be legal.

tools/runner
Now many tests includes UVM, so the default timeout may be too short.
=> Increase default timeout for UVM

tests/chapter-18/18.5.1--explicit-external-constraint_1.sv, tests/chapter-18/18.5.10--variable-ordering_1.sv, tests/chapter-18/18.5.14--soft-constraints_2.sv, tests/chapter-18/18.5.2--pure-constraint_2.sv, tests/chapter-18/18.5.4--distribution_2.sv, tests/chapter-18/18.6.3--behavior-of-randomization-methods_4.sv, tests/chapter-18/18.6.3--behavior-of-randomization-methods_5.sv, tests/chapter-18/18.8--disabling-random-variables-with-rand_mode_4.sv, tests/chapter-18/18.8--disabling-random-variables-with-rand_mode_5.sv, tests/chapter-18/18.9--controlling-constraints-with-constraint_mode_1.sv, tests/chapter-18/18.9--controlling-constraints-with-constraint_mode_2.sv, tests/chapter-6/6.19--enum_value_inv.sv, tests/generic/typedef/typedef_test_28__bad.sv
This PR adds `:type: simulation` to some tests which should be failed by semantic error.
Signed-off-by: Naoya Hatta <dalance@gmail.com>
=> Add :type: simulation

conf/generators/templates/sampled-functions-gclk.json, conf/generators/templates/sampled-functions.json
The $*_gclk functions per IEEE require global clocking to be legal.
Also these functions are only legal in assertion contexts in some simulators/formal tools.
Not done but advisable would be a test that checks tools error on gclk without global clocking defined.  I wouldn't check for only assertion contexts as many simulators e.g. Verilator don't care.
=> gclk functions require global clocking

tools/runners/Slang.py
The top-module config wasn't being passed to slang, so this fixes that. Also there are a bunch of elaboration tests that I'd like to test slang with, so remove the restriction of just preprocessing and parsing.
=> slang runner: Specify top module, run on elaboration tests

tests/generic/class/class_test_26.sv, tests/generic/class/class_test_27.sv, tests/generic/class/class_test_28.sv, tests/generic/class/class_test_29.sv, tests/generic/class/class_test_49.sv, tests/generic/class/class_test_53.sv, tests/generic/class/class_test_58.sv, tests/generic/class/class_test_7.sv, tests/generic/iface/iface_class_test_9.sv, tests/generic/member/class_member_test_15.sv, tests/generic/member/class_member_test_18.sv, tests/generic/member/class_member_test_19.sv, tests/generic/member/class_member_test_2.sv, tests/generic/member/class_member_test_25.sv, tests/generic/member/class_member_test_26.sv, tests/generic/member/class_member_test_27.sv, tests/generic/member/class_member_test_3.sv, tests/generic/member/class_member_test_31.sv, tests/generic/member/class_member_test_32.sv, tests/generic/member/class_member_test_4.sv, tests/generic/member/class_member_test_5.sv, tests/generic/member/class_member_test_6.sv, tests/generic/member/class_member_test_7.sv, tests/generic/member/class_member_test_8.sv, tests/generic/member/class_member_test_9.sv
A bunch of the class tests were invalid for various reasons; most of them because extern methods had no out-of-block implementation provided, or because undeclared types were used.
=> Fix broken class tests

tests/chapter-7/arrays/associative/other.sv, tests/chapter-7/arrays/associative/wildcard.sv
Trivial movement of tests needing wildcard associative arrays to be consistently in 7.8.1.
=> Move tests needing assoc wildcards consistently under 7.8.1

generators/ivtest
This blacklists those ivtests that are not legal code, and even Icarus is marked as not passing.
There are still a few tests Icarus fails, but these are believed valid code (e.g. Verilator passes them).
=> Blacklist Icarus tests that aren't legal code that Icarus fails

generators/path_generator
This is needed to include the fake topmodule code added earlier.
Closes #1160
=> Include the actual test code in path-generator tests

conf/generators/meta-path/hdlconvertor.json
This blacklists hdlconvertor tests that are not legal.
=> Blacklist hdlconvertor tests that are not legal.

tools/runners.mk, tools/runners/VeribleExtractor.py
This adds a runner for `verible-verilog-kythe-extractor`. It detects failure by checking if there were any log messages on stderr, as the tool's exit status is zero even for invalid files.
The verible submodule has been bumped manually, as `verible-verilog-kythe-extractor` changed significantly since the last bump (which happened more than a month ago).
=> Add verible verilog kythe extractor runner

.github/workflows/sv-tests-ci.yml
Otherwise it seems to be triggered two times (push and PR) for each
dependabot PR (which pushes to dependabot specific branches without a
fork).
=> Trigger GHA push action only on the master branch

conf/report/log-template.html, tools/runner, tools/sv-report
When looking at failing tests on the dashboard it would be helpful to know how long since they last ran.  This adds a date stamp.
=> Report test completion date stamp.

generators/ivtest
There likely needs to be some more tweaks added to how the list files are handled but I think this should fix the merge issue in #1205
=> Do not use the obsolete regress-v10.list in ivtest

generators/ivtest
This removes a bunch of items that were blacklisted, but with the recent changes I made to the exclude list generation they should not longer even be available for removal.
=> Remove ivtest blacklist items already excluded

tests/chapter-18/18.5.5--uniqueness-constraints_0.sv
inside_expression can take a expression at the left side of `inside`.
Therefore `b1, b2` can't be taken.
```
inside_expression ::= expression inside { open_range_list }
```
Signed-off-by: Naoya Hatta <dalance@gmail.com>
=> Fix syntax error of inside expression

generators/ivtest
Update both ivtest and icarus to the latest versions. Update the ivtest exclusion list to match the latest changes in ivtest.
Add back in $getpattern test (warn_opt_sys_tf) which is covered in the "Optional system tasks and system functions" annex of the standard.
=> Update ivtest and icarus to the latest and update ivtest exclusion list

.github/workflows/install.sh, conf/environment.yml
This PR is fixing old verilator version in conda environment. Basically, conda was getting this package from channel `conda-forge` instead of `symbiflow`. I forced all packages listed as jobs to be fetched from channel symbiflow. Additionally I also had to change `sed` command in `install.sh` to take into account new dependency format while uncommenting packages.
Creating this as draft in order to make sure that CI is ok.
=> Conda channels fix

.github/kokoro/run.sh
As the HTML results being in the gh-pages branch end up with a rather
large and slow to clone repository, the results have been moved to their
own repository.
This makes the CI push to that repository instead.
Fixes #1179.
=> kokoro: Push to SymbiFlow/sv-tests-results repository.

.github/add-local-submodule-inner.sh, .github/workflows/sv-tests-ci.yml
Using the tips found in https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/ this changes all the submodules to use "treeless" clones.
> * `git clone --filter=tree:0 <url>` creates a treeless clone. These clones download all reachable commits while fetching trees and blobs on-demand. These clones are best for build environments where the repository will be deleted after a single build, but you still need access to commit history.
This makes the amount of data downloaded significantly smaller. This reduces the time taken to clone all the submodules by about a third and helping with https://github.com/SymbiFlow/sv-tests/issues/1241 a bit (30m -> 17m).
=> Use treeless clones for submodules

README.md, tools/runners.mk
Also:
o Add uhdm targets and Antmicro yosys to runners.
o README: Add -k to suggested makefile call to build as many
targets as posible.
=> Adapt runners.mk to compile uhdm targets (changed in uhdm-integration).

tools/runners/VeribleExtractor.py
Two fixes for how results are interpreted:
* Segfaults are reported as failures
* `Re-defining macro` warnings do not cause test failure
=> VeribleExtractor: detect segfaults and ignore redefined macros

generators/ivtest
=> Update ivtest with code cleanup

generators/ivtest
Icarus and ivtest have been updated to return a runtime error (RE) for system tasks/functions that are used incorrectly. This resolves a number of issues seen by other tools where they were indicating an error and Icarus was only generating error messages and not a failing state.
=> Update ivtest/iverilog and cleanup exclude

.github/workflows/sv-tests-ci.yml, conf/environment.yml
This PR changes the conda channel from `symbiflow` to `litex-hub`.
This change additionally gives ability to replace `antmicro-yosys` package with `antmicro-yosys-complete` which is a metapackage that contains Antmicro Yosys fork and Yosys plugins.  Then we can remove explicit `symbiflow-yosys-plugins` dependency that forces yosys build on each CI job.
=> Change conda channel to litex-hub

generators/ivtest
Update to the latest ivtest repo and add a few more tests to the exclude list that are defacto standard/supported by commercial simulators.
=> Update ivtest and exclude list

tools/runners/UhdmYosys.py
Newest PR in ``litex-conda-eda`` changed name of ``uhdm-yosys`` binary: https://github.com/litex-hub/litex-conda-eda/pull/76
This PR adapts UhdmYosys runner to new name.
=> uhdm-yosys: adapt binary name to newest package

.github/kokoro/run.sh
This PR adds activating conda env in analysis subshell which is needed for fixing `module not found` error in kokoro run: https://source.cloud.google.com/results/invocations/f72adf9f-b967-475c-bf16-889bfd2ab476/targets/foss-fpga-tools%2Fsv-tests%2Fcontinuous/log
=> report-analyzer: kokoro: fix ImportError

tools/runners/UhdmYosys.py
The test for ibex core and UhdmYosys tool finishes with the following error:
```ERROR: Module `\work_ibex_core' not found!```
This commit fixes it.
Signed-off-by: Joanna Brozek <jbrozek@antmicro.com>
=> Fix module path for UhdmYosys tool

conf/lrm.conf, tests/chapter-15/15.5.1--named-event-trigger-blocking.sv, tests/chapter-15/15.5.1--named-event-trigger-non-blocking.sv, tests/chapter-15/15.5.2--named-event-wait.sv
These are described in chapter 15.5 of the LRM.
The tests cover direct and hierachical references to events within
modules, as well as direct references within a class.
=> Add tests for triggering and waiting for named events

Makefile, conf/fusesoc-configs/earlgrey.yml, conf/fusesoc-configs/ibex.yml, generators/fusesoc
Ref: #998, #315
Port swerv core to fusesoc and change the fusesoc configuration file for ibex and earlgrey cores.
It fixes verilator and surelog tests for Ibex and swerv cores.
=> Port swerv core to fusesoc

.github/workflows/sv-tests-ci.yml
dependabot creates new branches in the same repo and triggers the CI
twice (for push and for PR).
=> Run CI trigger only on master

tools/runners/UhdmVerilator.py
This PR fixes bad top module paths in UHDM verilator tests: ```%Error: Specified --top-module 'work_top' was not found in design.```
=> Uhdm verilator runner fix

generators/ivtest
There were a few tests that had the same name and were on the different lists. The generator was assuming that each test has distinct name and iterated through the list of lists of tests in undeterministic order. The tests with the same names were overwriting one another.
I made the iteration deterministic and tests names distinct by adding a list names as their prefixes.
=> Make sure ivtests generates tests with unique names

.github/workflows/install.sh, .github/workflows/run.sh, .github/workflows/sv-tests-ci.yml, Makefile, tools/check-runners
Some runners are dependent to other runners, so they have to be installed. Now they are tested in these jobs and in their own jobs too, which results in duplication of tests results.
E.g.:
uhdm-yosys uses surelog as frontend and sv-tests are detecting it as separate tool and are running it one more time.
I fix it by adding possibility to filter tools in Makefile and run tests only on selected runners. I also add usage of MAKEFLAGS field in sv-tests-ci.yml.
=> Add possibility of filtering tools

tools/runners/tree_sitter_verilog.py
This should work around the issues found in: https://github.com/SymbiFlow/sv-tests/pull/1379/checks?check_run_id=2046877086. Note that this doesn't really fix the runner, it allows the CI to finish despite the updated runner package being broken.
=> Catch exception thrown by tree-sitter

Makefile
I added sorting of runners names, because it was required to compare their lists correctly.
This should fix the kokoro build failures.
I also swapped RUNNERS and RUNNERS_FOUND variables in warning logs.
=> Add sorting of runners names before comparing them

conf/generators/templates/uvm-classes_2.json, tests/chapter-18/18.13.4--get_randstate_0.sv, tests/chapter-18/18.5.11--static-constraint-blocks_1.sv
Fixed a few issues in various UVM tests:
1. strings are not comparable to null, so changed to empty string
2. One test was trying to make a function call statement in the middle of a class body which is invalid
3. The generated uvm_classes_2 tests were not providing parameters to the super class constructor
Signed-off-by: MikePopoloski <mike@popoloski.com>
=> Fixes for UVM tests

.github/workflows/comment-pr.yml
The workflow for the commenter is started not only in pull requests, but also after the PR is merged, e.g: https://github.com/SymbiFlow/sv-tests/actions/runs/729723318
This PR is an attempt to stop that.
=> Don't run PR commenter on master

tools/runners/Surelog.py
This PR is adding -sverilog flag to Surelog for black-parrot tests. Reported in: https://github.com/SymbiFlow/sv-tests/issues/1438
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
=> Add -sverilog to Surelog cmd for black-parrot test

tools/runners/Slang.py
Some of the imported test groups are not semantically valid SystemVerilog, so set flags in the slang runner to only do parsing.
=> slang runner: Set --parse-only for certain test groups

conf/generators/meta-path/hdlconvertor.json, conf/generators/meta-path/utd-systemverilog.json
The two hdlconv tests use `wire` as a function return type which is not allowed and doesn't make much sense anyway (wire is not a data type, it's a net type).
The utd test is just lexically broken, it's missing a closing quote on one of its strings.
=> Blacklist a few broken tests from hdlconv and utd

.github/workflows/comment-pr.yml
They served their purpose. The previous PRs fixed the checks, the log
messages can be removed now.
=> Remove debug logs in PR commenter

conf/generators/meta-path/yosys-memories.json, conf/generators/meta-path/yosys-simple.json, conf/generators/meta-path/yosys-sva.json, conf/generators/meta-path/yosys-svinterfaces.json, generators/yosys_hana
Blacklisting tests because:
* The hana "test_parser" test has messed up syntax around a macro expansion; it seems like the test is assuming the tokens will automatically concatenate with each other. No commercial tool I tried can parse this and the LRM does not seem to allow it either.
* memories_issue00335 references a parameter before it's declared
* simple_func_width_scope uses a function declared inside a generate block in a constant expression. This is directly disallowed by the LRM.
* simple_named_genblk references an unnamed generate block by name which is not allowed (and makes no sense anyway).
* sva_basic04 tries to bind a module to a "top" instance even though there is no such instance.
* sva_basic05 tries to instantiate a module called "demo" even though there is no such …
=> Blacklist broken yosys tests

conf/fusesoc-configs/earlgrey.yml, conf/fusesoc-configs/ibex-sim.yml, conf/fusesoc-configs/ibex-synth.yml, conf/fusesoc-configs/swerv.yml, generators/fusesoc, tools/runner, tools/runners/Surelog.py, tools/sv-report
Add the possibility to build cores without  `-noelab` argument for Surelog tool.
=> Allow build cores without `-noelab` argument for Surelog tool

.gitmodules
Don't use a repository fork.
Signed-off-by: Joanna Brozek <jbrozek@antmicro.com>
=> Change url for ibex-yosys-build submodule

.github/workflows/sv-tests-ci.yml, conf/environment.yml, tools/runners/UhdmVerilator.py, tools/runners/UhdmYosys.py
``uhdm-integration-*`` packages were removed in PR: https://github.com/hdl/conda-eda/pull/106 as this packages were shipped with different version of ``surelog`` then version that was used to built ``yosys``/``verilator``.
Now ``surelog`` is part of ``yosys-uhdm``/``verilator-uhdm`` packages. 
This PR changes used package name and adapts rest of the scripts. This should solve random ``segmentation faults`` caused by incompatible versions of ``surelog`` used to generate UHDM file with version used to compile tool.
=> Change verilator-uhdm and yosys-uhdm package names

conf/generators/meta-path/basejump.json
* Add various missing package references
* Add missing include directory
* Blacklist the package files, since otherwise the package tests will include the packages multiple times causing errors
=> Fix basejump STL test setup

generators/ivtest
Reasons are given in comments. See also #1271
=> Blacklist additional ivtests

tests/chapter-14/14.3--clocking-block-signals.sv, tests/chapter-14/14.3--clocking-block.sv, tests/chapter-14/14.3--default-clocking-block.sv, tests/chapter-14/14.3--global-clocking-block.sv
These tests declared local variables with names that collide with module port names.
```
../../src/github/sv-tests/tests/chapter-14/14.3--clocking-block.sv:15:18: error: redefinition of 'clk'
module top(input clk);
^
../../src/github/sv-tests/tests/chapter-14/14.3--clocking-block.sv:17:6: note: previous definition here
wire clk;
^
```
=> Fix broken clocking block tests

conf/generators/meta-path/basejump.json
bsg_1_to_n_tagged_fifo_shared.v: Uses a genvar outside of a generate loop, and declares two generate blocks with the same name which is illegal.
```
../../src/github/sv-tests/third_party/cores/basejump_stl/bsg_dataflow/bsg_1_to_n_tagged_fifo_shared.v:238:54: error: 'i' does not refer to a value
assign valid_o = valid_o_tmp | (unbuffered_mask_p[i] & tag_one_hot_or_not[i]);
^
../../src/github/sv-tests/third_party/cores/basejump_stl/bsg_dataflow/bsg_1_to_n_tagged_fifo_shared.v:242:6: error: redefinition of 'rof'
begin: rof
^
../../src/github/sv-tests/third_party/cores/basejump_stl/bsg_dataflow/bsg_1_to_n_tagged_fifo_shared.v:99:6: note: previous definition here
begin: rof
^
```
bsg_mem_multiport.v: References variable "harden_p" which doesn't exist anywhere.
``` …
```
=> Blacklist broken basejump tests

tests/chapter-14/14.3--clocking-block-signals-error.sv
One of the clocking block tests was invalid because it tried to assign to nets from within a procedural context. This diff adds a should_fail to that test and adds a new duplicated test with the original error fixed.
=> Fix clocking block test, add a should_fail test to mirror

generators/tnoc
Without this we get plenty of errors like this:
```
slang-driver --single-unit --top=tnoc -I /tmpfs/src/github/sv-tests/tests/generated/tnoc  (...)
error: no such file or directory: 'tests/generated/tnoc/tnoc.sv'
```
=> Use absolute path to TNoC test top file

conf/report/report.css
Signed-off-by: Prahitha Movva <prahitha.movva03@gmail.com>
When using search, the width/position of the first column is not consistent. This PR fixes the issue by making the width of the first column 30em always.
Previously (when the first column is not long/wide enough):
=> minor ui fix

generators/black-parrot
This diff fixes the file lists for some of the black-parrot tests. The other file lists has some problems, and the bp_top file list contains all necessary files for all potential tops so it seems easiest to just use that for all tests.
1. The bp_me file list contains a reference to a nonexistent include directory.
2. The bp_fe and bp_be lists didn't include all of the modules needed to elaborate the core.
3. Some of the tests, such as bp_lce, didn't even include the bp_lce module/file in their test list! Using the bp_top list means that we're actually testing the top modules we think we are.
=> Fix black-parrot test file lists

generators/ariane, tools/runners/Slang.py
This fixes the Ariane build for the slang runner. Two problems fixed:
1. The Ariane target we're using doesn't build if you don't define VERILATOR, since it otherwise references nonexistent modules.
2. The filelist includes "axi2apb_wrap.sv" which tries to use nonexistent interfaces. axi2apb_wrap is never used anywhere itself so it's fine to just remove it.
=> Fix Ariane core build

conf/fusesoc-configs/ibex-sim.yml, conf/fusesoc-configs/ibex-synth.yml, generators/fusesoc, tools/BaseRunner.py, tools/runner, tools/runners/UhdmVerilator.py, tools/runners/Verilator.py
This makes it possible for simulation tools to build the Ibex core (and changes slang to not use the synthesis target).
- vlt and cc files need to be filtered out for all non-verilator tools
- Even Verilator couldn't build the Ibex core because the fusesoc generator wasn't including the necessary defines
=> Fix ibex test

tools/runners/Slang.py
This works around a couple test issues by modifying the slang runner. Both are described via comments in the code, so see that for more details. The broken earlgrey configuration is tracked in #1564 and the black-parrot syntax error was fixed by myself here: https://github.com/black-parrot/black-parrot/pull/843
=> Add a couple workarounds to the slang runner

.github/workflows/comment-pr.yml
We store the artifacts differently now that we have the full report
uploaded.
=> Fix PR commenter action

tools/runners/VeribleExtractor.py
Sets correct file list root and makes sure all paths in the file list are absolute.
=> VeribleExtractor: Set correct file list root

.github/workflows/sv-tests-ci.yml, conf/report/report-template.html, tools/sv-report
Should fix #1641 
From the feedback earlier:
- the datetime can be generated in Python
- the report-template should probably use the passed build_id from Python for checking the ID
=> footer detail

tests/chapter-9/9.4.2.4--event_sequence.sv
Assigning to nets from a procedural context is not allowed, so make them variables instead.
Example error:
```
../..tests/chapter-9/9.4.2.4--event_sequence.sv:30:10: error: cannot assign to a net within a procedural context
@seq y = 1;
^
```
=> Fix event_sequence test

.github/workflows/comment-pr.yml, .github/workflows/compress.sh, .github/workflows/sv-tests-ci.yml
It does not need the whole report, it is faster and saves us some quota
for the remaining artifacts where they are actually used.
=> Don't upload all the output for the PR commenter

.github/workflows/summary.sh, .github/workflows/sv-tests-ci.yml, conf/report/history-graph-template.html, conf/requirements.txt, tools/history-graph
Closes #1636
This adds a simple history graph (generated using commits from the sv-tests-results).
Currently it looks like this:
It uses a MIT licensed https://www.chartjs.org/ library.
TODO:
=> Add history graph util

conf/report/history-graph-template.html
Changes:
* Added proper labels to x and y axis
* Changed the graph type to stepped (no diagonal lines, which suggest "guessing" what happened in between builds)
* When hovering the cursor over a tool name in the legend, all other tools are faded out - this makes it easier to identify the graph for a given tool, example below
=> History graph improvements

generators/ivtest
The Icarus test-case program3b wants non-blocking assignments in final-blocks to fail parsing.   A strict reading of 1800-2017 $9.2.3 does not require this, even though the non-blocking assignment will have no effect since there is no next tick in which the value will update.
Simulators do not handle this consistently:  VCS allows it, Questa disallows it, and Xcelium prints a warning.
Slang will also be handling this as a Warning.  See https://github.com/MikePopoloski/slang/discussions/405 and https://github.com/MikePopoloski/slang/pull/406
=> Add ivtest/program3b to blacklist

tools/runners/Sv2v_zachjs.py
Similar logic already exists in other runners. Relevant tests which previously failed now appear to pass.
=> sv2v runner: support defines

conf/report/history-graph-template.html
By default the sort done by jinja2 is not case sensitive.
=> history: sort tools by name in legend

tools/runners/UhdmYosys.py, tools/runners/Yosys.py, tools/runners/YosysSv.py
Currently the runner for UHDM-Yosys runs more commands than the ones for vanilla Yosys and Yosys-SV, which results in an unfair comparison. This PR adds the missing commands to the Yosys and Yosys-SV runners. It also removes the `-check` flag from the `hierarchy` command, as it would cause some tests to fail (like this one: https://chipsalliance.github.io/sv-tests-results/#UhdmYosys|utd-sv|utd-sv_bw_dtl_impctl_pulldown).
It also cleans up the UHDM-Yosys runner a bit (imports, unused vars).
=> Make Yosys, Yosys-SV and UHDM-Yosys runners equivalent

tests/chapter-15/15.4--mailbox-blocking.sv, tests/chapter-15/15.4--mailbox-non-blocking.sv
The mailbox tests have a syntax problem where variables are defined after functional logic in the initial block.   Slang detects this and gives a valid error. The fix is to move the mailbox creation to be after the variable declarations.
```
tests/chapter-15/15.4--mailbox-blocking.sv:21:2: error: declaration must come before all statements in the block
string msg = "abc";
^
```
=> Fix mailbox test variable declarations

tools/history-graph
When generating the report and the history graph, current results are
not yet committed. We have to handle them separately.
fixes #1707
=> history: take not yet committed changes into account

generators/black-parrot
bp_lce and bp_uce are not valid top level modules according to the rules of SystemVerilog. slang correctly points this out:
```
error: 'bp_uce' is not a valid top-level module
```
Since everyone was so against removing these tests I propose just removing the top level specifier for them, which means nothing will be instantiated or elaborated for these tests. I don't see how it can work any other way without removing them completely.
=> Remove top module specifier for bp_lce and bp_uce tests

.gitmodules, conf/generators/meta-path/projf-explore.json
Signed-off-by: Tomasz Jurtsch <tjurtsch@antmicro.com>
This PR adds https://github.com/projf/projf-explore as submodule and template for path_generator
=> Add tests from projf/projf-explore repo

.github/workflows/lint-review.yml, .github/workflows/trigger-lint.yml
This PR adds CI scripts that use [Verible Lint Action](https://github.com/chipsalliance/verible-linter-action)
to automatically review the changes in `.v` and `.sv` files.
You can see an example of how this works here:
https://github.com/antmicro/gha-playground/pull/84
In order to post comments, the action needs a proper token.
Due to restrictions described [in the docs](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) It's not possible to create comments
in the context of `pull_request` from an external repository.
To tackle this problem we create two workflows:
The first workflow triggered by `pull_request` stores information
about the PR in artifact and triggers the main workflow.
The main workflow runs the Action using a token …
=> [ci] Add GHA workflows to review PRs using Verible

tests/chapter-18/18.17.2--if-else-production-statements_0.sv, tests/chapter-18/18.17.2--if-else-production-statements_0_fail.sv, tests/chapter-18/18.17.2--if-else-production-statements_2_fail.sv, tests/chapter-18/18.17.3--case-production-statements_0_fail.sv, tests/chapter-18/18.17.6--aborting-productions-break-and-return_2_fail.sv
Some of the randsequence tests referenced undeclared variables or had typos in their production names. This PR fixes them, and adds new tests that exercise the failing paths with a should_fail_because to make sure tools actually catch these kinds of errors since they are easy to make.
=> Fix randsequence tests

tools/runners/Slang.py
Two things handled here:
* If the top module field is an empty string, don't pass it along to the slang driver.
* projf tests aren't able to be elaborated so force parsing-only for them.
=> Fixes for the slang runner

.github/workflows/lint-review.yml
We decided to keep the 'main' version until we make it stable, so I'm changing this.
We'll be able to apply fixes more easily.
=> set verible action version to 'main'

conf/generators/meta-path/yosys-simple.json, conf/generators/meta-path/yosys-svinterfaces.json, generators/ivtest, tests/chapter-16/16.2--assert-final-uvm.sv, tests/chapter-16/16.2--assert0-uvm.sv, tools/runner, tools/runners/Slang.py
Blacklisting one ivtest:
- event_array is marked as "should fail" but actually is totally fine (and passes in all major simulators)
Blacklisting three yosys tests:
- load_and_derive and ondemand appear to be helper files part of a larger test and do not pass in isolation (and also have some invalid syntax naming a module "ref" which is a keyword)
- mem2reg_bounds_tern references an out of bounds array element at compile time -- you could argue this should pass with a warning but it's a nonsensical operation
Two assert uvm tests were invalid; they had a begin/end pair as the action block of a deferred assertion, which is disallowed by the LRM:
```
../..tests/chapter-16/16.2--assert0-uvm.sv:60:47: error: deferred assertion action must be a subroutine call
assert #0 (m_if.a != m_if.b) else …
```
=> Random collection of test fixes

tests/chapter-20/20.14--coverage.sv
Adds a test to cover parsing of the system tasks and functions defined in chapter 20.14.  This test-case also includes the pre-defined coverage macros defined in 40.3.1.
=> Add tests/chapter-20/20.14--coverage.sv

.github/workflows/sv-tests-ci.yml, tools/runners/UhdmYosys.py
This PR adds tool filter for uhdm-verilator and uhdm-yosys tools and fixes uhdm-yosys binary name to expected one.
=> CI: add missing tool filter; fix uhdm-yosys binary name

generators/path_generator, tests/chapter-14/14.3--clocking-block-signals-error.sv, tests/chapter-18/18.17.2--if-else-production-statements_0_fail.sv, tests/chapter-18/18.17.2--if-else-production-statements_2_fail.sv, tests/chapter-18/18.17.3--case-production-statements_0_fail.sv, tests/chapter-18/18.17.6--aborting-productions-break-and-return_2_fail.sv
Currently all test cases from ``projf-explore/hello/hello-nexys/{A..I}/top.sv``are generated as: ``tests/generated/projf-explore/projf_top.sv``. This PR adds path from the test directory (with ``/`` changed to ``_``) to the name of the test and fixes this problem.
Now all test have unique test name.
=> Generate unique test name in path_generator

tools/history-graph
Add null datapoints for tools that do not have any data for a specific
date (e.g. the tool has just been added, was broken for a moment, etc).
Fixes #1858
=> Fix history graph

tests/chapter-25/25.3-interface.sv
Fixes 25.3-interface passing the wrong top-module to Verilator.
=> 25.3-interface.sv: Fix wrong top_module

generators/ivtest, tools/runners/Yosys.py
This PR changes ``yosys`` cmd to add ``-defer`` option only when test is not marked as ``elaboration``. It makes ``yosys`` to fail on tests that uses e.g. ``$display`` with invalid/unsupported format specifier or on unsupported ``$finish`` call.
=> Add -defer to yosys cmd in not elaboration tests only

tools/check-runners, tools/runners/moore.py
This PR fixes ``moore-parse`` runner and disables caching exception when loading runner module in ``check-runner``.
=> Fix moore-parse runner

generators/ivtest
Now all ivtest tests have ``simulation parsing`` type
=> Fix multiple type attribute in ivtest generator

tools/runners/Yosys.py
The clifford.at domain does not resolve anymore.
=> Update Yosys project URL.

conf/report/log-template.html, conf/report/report-template.html, conf/report/report.css, conf/report/report.js, tools/sv-report
* Reduced index.html file size
`index.html` size changed from 9.4M to 385K.
Details about every tested (tag, tool) pair (a "result cell") has been moved to 4490 (= number of result cells) config files with cumulative size of about 3.3M.
Config file for a result cell is loaded only when its details panel is opened.
Numbers above come from a report containing results for 14 tools and 326 tags.
In case this amount of config files is problematic, it shouldn't be a problem to e.g. merge all configs of a single tag, reducing the number of files to 326.
* URL hash replaced with URL query parameters
Before: `.../#moore|22.11|22.11--pragma-complex`
After: `.../?v=moore+22.11+22.11--pragma-complex`
The hash is still checked and parsed when `v` parameter is absent, so all existing links will work. …
=> Report: Reimplement test preview panel, reduce index.html file size

conf/report/code-template.html, conf/report/code.css, conf/report/details-view.css, conf/report/filter.js, conf/report/log-template.html, conf/report/log.css, conf/report/report-template.html, conf/report/report.css, conf/report/report.js, tools/runner, tools/sv-report
The PR implements `results_group` property that can be added to tests. Separate table in the report is generated for each group.
For simplicity, the results group ID can only contain characters `[0-1a-z_]`. To assign nice display name to a group, add an entry to `RESULTS_GROUP_DISPLAY_NAMES` in `tools/sv-report`. By default no name is displayed.
The default group ID (the one assigned to tests without group set) is empty string `""`.
Patch that tags some tests and adds display names for a few groups: https://github.com/antmicro/sv-tests/commit/0bfdf01e4c7d3ecc11a28f6122d6e1d10b5463ac.patch
There are also a few other changes (sorry for "all in one" PR :) ):
* Slightly improved test details panel style
* Faster and better looking sorting. Fractions with the same value are additionally …
=> Add results_group property (...and a new filter)

.github/workflows/sv-tests-ci.yml, Makefile
Some tests are using a lot of RAM/CPU and starves other tests.
This results in instability in the report.
Tests from the BIG_GENERATORS variable is now run without -j flag.
=> Add BIG_GENERATORS variable

tests/chapter-11/11.4.14.3--unpack_stream_inv.sv
On Verilator the generic Verilator tool harness disables this warning due to noise in other tests, so this specific test needs to re-enable it.
=> Fix 11.4.14.3--unpack_stream_inv.sv on Verilator

conf/generators/meta-path/basejump.json, conf/generators/meta-path/hdlconvertor.json, conf/generators/meta-path/hdlconvertor_std2012.json, conf/generators/meta-path/hdlconvertor_std2017.json, conf/generators/meta-path/projf-explore.json, conf/generators/meta-path/utd-systemverilog.json, conf/generators/meta-path/yosys-asicworld.json, conf/generators/meta-path/yosys-errors.json, conf/generators/meta-path/yosys-memories.json, conf/generators/meta-path/yosys-simple.json, conf/generators/meta-path/yosys-sva.json, conf/generators/meta-path/yosys-svinterfaces.json, generators/ariane, generators/black-parrot, generators/fusesoc, generators/fx68k, generators/ivtest, generators/path_generator, generators/rsd, generators/scr1, generators/tnoc, generators/yosys_hana
This uses the feature added in #1959 to sort tests into various result groups.
Most of the tests are still ungroupped.
There are two new groups:
* cores - where we put all big desings/riscv cores
* imported - which contains regression test suites imported from other tools
It might be worth to move all UVM tests to a group of its own too but it's not done here.
=> Make use of the results_group

conf/requirements.txt
This is a dependency of Surelog/UHDM packages.
See: https://github.com/chipsalliance/UHDM/issues/602
At the moment we don't have a way to install python dependencies to
individual tools, but this is a small package so let's install it
globally.
=> Add orderedmultidict to pip dependencies

conf/report/report-template.html
Test case: select cell in TNoC row (table "cores").
=> Fix disappearing cell selection on rows with non-lowercase tag

conf/fusesoc-configs/earlgrey.yml
This creates a new UVM row in the Cores tab which is misleading and looks like a bug.
CC @hzeller
=> Remove uvm tag from earlgrey

tools/runners.mk
This PR adapts to new (not yet merged) version of ``yosys-uhdm-plugin-integration`` that removes BUILD_UPSTREAM variable from uhdm-plugin.
Requires: https://github.com/antmicro/yosys-uhdm-plugin-integration/pull/307, https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/186
=> Adapt to new version of yosys-uhdm-plugin-integration

.gitmodules, tools/runners.mk
Currently we always try to install latest moore. This way we cannot really track/control the version. Current version breaks the CI at the moment.
=> Build moore from a submodule

conf/report/report-template.html, tools/sv-report
No need to store config and a TODO if we don't intend to use any, the id should be okay to display
=> Use results group id as the header

.github/workflows/sv-tests-ci.yml
Otherwise if we restart the CI, or trigger a rebase with a comment, the actor is different and automerge doesn't work.
=> Check pull request author instead of action actor for automerge

generators/ivtest
30s is still too small timeout value for Surelog to parse long ivtests. Locally it takes about 60s to parse them, so here I increase timeout to 360s.
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/361
=> Increase timeout for long ivtests

conf/fusesoc-configs/swerv-sim.yml
Simulation mode should be enabled when it will be possible to generate simulation binary without run it automatically.
=> Change swerv-lint to swerv-sim.

Makefile
Before this change, the `RUNNER_PARAM` variable in line 71 was always empty.
=> Move RUNNER_PARAM assignment outside the define

.github/workflows/sv-tests-ci.yml
Github caches tend to get buggy with GCP runners that we use here.
If they work correctly, the caches are set up in ~45s max.
If they don't, this steps tends to take over 360 minutes (the default
timeout) and break the CI.
This patch tries to workaround this problem by setting the timeout to 3
minutes but making the cache step optional. If we fail to set up caches,
just build everything normally, it will be quicker anyway.
=> Improve github cache handling

conf/report/history-graph-template.html
There are days where there are fewer or more builds that 1 a day. Each
build generates a new entry in the history graph.
Without this change, each entry created a new evenly separated data
point which didn't really make sense when analyzing the history.
With this change the data points will be split in accordance to the
actual build timestamp.
As a side benefit we have a nicer formatting of the dates.
Full timestamps can still be checked by hovering individual data points.
Before:
After:
=> history graph: properly interpret date in data points

generators/ivtest
This was recently changed from elaboration to simulation but that's not really correct; the tests don't really require simulation, but they do need elaboration in order for a bunch of them to pass -- most of the ones that are marked as should_fail require semantic analysis, not just parsing. Without setting elaboration, tools will fail to correctly fail on those tests.
Signed-off-by: MikePopoloski <mike@popoloski.com>
=> Add 'elaboration' mode back to ivtests

.github/workflows/report.sh, .github/workflows/sv-tests-ci.yml
This PR speeds up summary job by checking out only tests and cores instead of every submodule (including tools).
=> Checkout only tests and cores in summary

README.md
This PR changes Yosys link in readme to Github project page.
=> Fix yosys link in readme

tools/runner
The CI (and many local machines) mount tmpfs in RAM, this change
optimizes memory consumption which is crucial for some of the larger
designs here.
=> Don't use tmpfs for building

tools/runners/UhdmVerilator.py, tools/runners/UhdmYosys.py, tools/runners/VanillaYosysUhdmPlugin.py
To obtain valid UHDM we need to specify the top module to be used (or at least our best guess).
=> Specify top module when parsing UHDM

tools/runners/Slang.py
Change the test to parsing-only in the slang runner.
=> bp_multicore has an invalid config and cannot be elaborated

generators/ariane
The Ariane source list contains duplicate entries for some source files, which causes most tools to throw up errors about duplicated definitions. This diff filters out the duplicates to fix that.
=> Fix duplicate sources added to Ariane build

tools/runners/UhdmYosys.py
When using `-lowmem` with Surelog used as library it doesn't work as surelog tries to run argv[0] as a new command (to call itself) which in our case calls yosys directly.
This might lead to OOM errors instead though
=> UhdmYosys: do not use lowmem for Surelog

.gitmodules, tools/runners.mk
The antmicro-yosys does not build anymore with current compilers,
is not updated anymore and also not run in the tests anymore.
=> Remove ibex-yosys-build from runners build.

tests/chapter-12/12.6.1--case_pattern.sv, tests/chapter-12/12.6.1--casex_pattern.sv, tests/chapter-12/12.6.1--casez_pattern.sv
The tests have the wrong variable name in the case expressions.
=> Fix basic syntax errors in 12.6.1 tests

tools/runners.mk
* Compile yosys with gcc. This way all tools are compiled with the same compiler.
* Call bazel shutdown for verible, otherwise the bazel daemon keeps running, using up memory.
=> Tweaks to runners.mk: shutdown bazel; compile yosys with gcc

tests/generic/class/class_test_52.sv
IEEE 11.4.12.1 disallows zero size replication in the removed line.
=> Fix class_test_52.sv to be legal

generators/ivtest
This disables some ivtests that are mis-failures on Verilator (and perhaps others)
=> Disable some bad ivtests

tools/sv-report
On macOS, since Python 3.8, the default start method in multiprocessing module is set to "spawn". This requires some constraints to be met. For details, see https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming
This PR refactors the sv-reports scripts to met required constraints.
Tested on Linux with default ("fork") and "spawn" method (activated by calling `multiprocessing.set_start_method('spawn')`) and on macOS (where "spawn" is default).
=> Make sv-report compatible with 'spawn' start method.

tests/chapter-15/15.4--mailbox-blocking.sv, tests/chapter-15/15.4--mailbox-non-blocking.sv
This makes the mailbox tests check simulation results.  It also uses a specific type to avoid dependency on tagged union support.
Passes on Verilator master.
=> 15.4-mailbox tests: Enable simulation

tools/runners/Icarus.py
Currently when specifying a top-level module for the icarus runner the `-s` switch is passed together with the top-level module name as a single parameter. Both are separated by a space, e.g. `-s top`. This results in the space being included in the top-level module name, resulting in errors such as
error: Unable to find the root module " top" in the Verilog source.
Pass to the `-s` switch and the top-level module name as two separate parameters to fix this.
=> runners: icarus: Fix top-level module specification

.github/workflows/sv-tests-ci.yml
There is an issue with platform detection in bazel 6.0.0
Until this is fixed in Verible, use an older bazel version.
=> Use older bazel

tools/runners/Icarus.py
The icarus runner at the moment only supports parsing mode. Add support for the other modes as well.
* For `preprocessing` the `-E` flag is added in which case only the preprocessor is being executed.
* For `parsing` mode now the `null` backend is used to skip the code generation phase.
* For `elaboration` nothing special has to be done since it is the default behavior
* To support `simulation` a shell script is created that first executes the iverilog compiler and then if that is successful executes the resulting executable. This is similar to what other runners do.
=> runners: icarus: Support all modes

.github/workflows/comment-pr.yml, .github/workflows/sv-tests-ci.yml, .github/workflows/trigger-lint.yml
Latest points to jammy, this does not change the distro, but takes an older Jammy release.
The new one seems to not be compatible with Singularity (which we're using in our custom runners).
This change can be reverted once the Singularity issue is resolved. Alternatively we can switch to other distro (debian seems to work).
=> Temporarily use older ubuntu image

conf/report/report.css
There are a few minor issues with the current sv-tests dashboard stylesheet. 
I have addressed:
- sticky navbar
- adjusting the height and width of cells
- filter / search / footer sections do not move when scrolling
- better sticky table columns
- overlapping borders
=> visual sv-tests dashboard improvements

conf/generators/meta-path/yosys-simple.json, conf/generators/meta-path/yosys-svinterfaces.json
* module_scope_func - Uses a function declared inside a generate block as a constant expression, which is pretty straightforwardly not allowed by the LRM
* resolve_types - Has multiple problems: references an undeclared module, and uses a keyword as the name of a module.
=> Blacklist two invalid yosys tests

conf/report/code-template.html, conf/report/code.css, conf/report/log-template.html, conf/report/log.css
- added sticky (y and x axis) headers to log and code windows
- the background color of the log header instead of the list of properties now shows whether it is passed or not
=> Add sticky headers to log and detail panels

.github/workflows/sv-tests-ci.yml
Some tools have multiple submodules that isn't necessary to build them. This can lead to long initialization time.
This PR allows to initialize only specified submodules of tool that are required to build them.
This reduces initialization time of ``UhdmYosys`` from ``21m14s`` (https://github.com/chipsalliance/sv-tests/actions/runs/4932148067/jobs/8814894903) to ``1m11s`` (https://github.com/chipsalliance/sv-tests/actions/runs/4935639999/jobs/8822211039?pr=4404)
=> Initialize only required submodules of tool

.github/workflows/sv-tests-ci.yml, generators/black-parrot
Currently black-parrot generator uses different top modules for different cores, but they still have the same default configuration parameter (``e_bp_default_cfg``).
This PR updates black-parrot generator to use ``wrapper.sv`` with ``BP_CFG_FLOWVAR`` changed to proper configuration.
This PR also changes GHA machines to ``n2-highmem-16`` as now Surelog requires about ``70GB`` of RAM for largest black-parrot configuration.
=> Update black-parrot generator

.github/workflows/sv-tests-code-quality.yml
``SymbiFlow/actions/checks`` action only looks at top directory in ``third_party`` folder (e.g. it doesn't check recursively for ``LICENSE`` file in submodules of submodule): https://github.com/f4pga/actions/blob/main/checks/checks.py#L380.
This PR removes initialization of submodules recursively and also updates ``actions/checkout`` and  ``actions/setup-python`` version to newest stable. This reduces CI job time from ``29m 57s`` to ``2m 20s``.
=> CI: don't initialize submodules recursively; update actions version

.github/workflows/sv-tests-ci.yml
Moore build is currently broken in CI since one of its dependencies requires rust 1.60, but the CI only install rust 1.59.
Bump the rust version for the CI to 1.60 to fix this.
=> Fix moore build in CI

generators/ivtest, generators/rsd
* RSD core appears to need RSD_MARCH_FP_PIPE macro defined, otherwise tools that actually do error checking will tell you:
```
../../../third_party/cores/rsd/Processor/Src/FloatingPointUnit/FPDivSqrtUnit.sv:9:76: error: 'FPDivSqrtUnit' is not a modport of 'RecoveryManagerIF'
module FPDivSqrtUnit(FPDivSqrtUnitIF.FPDivSqrtUnit port, RecoveryManagerIF.FPDivSqrtUnit recovery);
^~~~~~~~~~~~~
```
* One ivtest entry has invalid table rows defined for a primitive, confirmed failure on commercial tools:
```
../../../third_party/tests/ivtest/ivltests/pr3587570.v:8:6: error: primitive table row has all 'x' inputs so its output must also be 'x'
? : 0;
^~~~~~
../../../third_party/tests/ivtest/ivltests/pr3587570.v:8:6: error: primitive table row duplicates a set of inputs with a different specified …
```
=> Fix two misc test issues

conf/requirements.txt
The version we used was pretty old, there were lots of changes in tree sitter verilog which hopefully allow us to use the latest py tree sitter.
Ref: #4549
=> Unfreeze tree sitter

conf/generators/templates/assignment-sim.json, conf/generators/templates/equality.json, conf/generators/templates/logical-equiv.json, conf/generators/templates/logical-impl.json, conf/generators/templates/logical.json, conf/generators/templates/operators-sim.json
The initial execution of a `assign` statement is scheduled in the same time slot as an `initial` block.
There are a few tests that use an `initial` block to evaluate whether an `assign` statement was correctly executed. But this leads to an inherit race condition as the `initial` block might run before the `assign` has been executed.
Switch these tests to use a `final` block instead to avoid the race condition.
=> Avoid race conditions between `assign` and `initial`

.github/workflows/sv-tests-ci.yml, generators/veer-config
=> Remove VeeR asserts from simulation builds

tools/BaseRunner.py, tools/runners/Icarus.py, tools/runners/Odin.py, tools/runners/Slang.py, tools/runners/Surelog.py, tools/runners/Sv2v_zachjs.py, tools/runners/UhdmVerilator.py, tools/runners/UhdmYosys.py, tools/runners/Verible.py, tools/runners/VeribleExtractor.py, tools/runners/Verilator.py, tools/runners/Yosys.py, tools/runners/moore.py, tools/runners/sv_parser.py, tools/runners/tree_sitter_verilog.py
This change adds commit hashes to project links that refer to GitHub repositories.
It should affect only the links used in the HTML reports of the results.
=> Refer to specific commits in GitHub links

generators/veer-config
UVM tests in VeeR use a different structure that is incompatible with the VeeR generator.
=> Skip the `uvm` directory in VeeR-EL2

conf/requirements.txt
The ``build_library`` call that tree-sitter-verilog uses has been deprecated in 0.22, we need to stick to an older version.
=> Freeze tree_sitter version

generators/ariane
A new envirnment variable `HPDCACHE_DIR` is used to replace some paths in the upstream repository. Replace it with the correct path.
I did not test this, but the generated list of files seems correct. Let's see if the CI agrees.
Fixes #5799
=> Fix ariane generator

generators/ariane
Ariane seems to require recursive filelists. This commit adds recursive filelist parsing to the Ariane generator.
I am trying to set up a local instance of sv-tests, but compiling all the runners takes a while. In the meantime, we can also check what the CI says.
This commit (hopefully) fixes #5807
=> Fix ariane generator (again)

.github/workflows/comment-pr.yml
This is required to post a comment after the latest changes in GH api.
=> Add PR write permissions to the comment bot

.github/workflows/sv-tests-ci.yml, README.md, tools/runners.mk
Unbreak the yosys-slang job after a submodule has moved, and add the tool to the README list.
=> yosys-slang updates

.github/workflows/sv-tests-ci.yml, README.md, tools/runners.mk
The parser is missing in the public report since I forgot to add a CI job for it. 
I simply added an entry in the RUNNERS_TARGETS var of the runners.mk file. Not sure if something else is needed. I also added it to the list of supported tools in the README.md
Let me know if something else is needed.
Thanks!
=> Add CI job for tree-sitter-systemverilog

tests/chapter-11/11.4.12--concat_op-bit_select.sv
Adds a testcase for 11.4.12.
Covers bit-selection of concatenated bit/logic vectors.
As indicated in LRM `11.4.12`
```
One or more bits of a concatenation can be selected as if the concatenation were a packed array with the range [n-1:0]. 
```
=> added testcase for 11.4.12

conf/generators/meta-path/basejump.json, generators/ivtest
Disables more illegal tests:
* bsg_mem_multiport_latch_write_banked_bypassing.sv - Bad commenting makes illegal "end"
* bsg_mem_multiport_latch_write_banked_bypassing_sync.sv - Likewise
* implicitport2 - Already in disables, but had extra _ so was not blacklisted.  (Test has multiple modules out of order, which breaks test harness.)
* implicitport3 - Likewise.
* implicitport6 - Likewise.
=> Disable bsg_mem_multiport_latch* and implicitport/2/3/6

.github/workflows/sv-tests-ci.yml
`cache@v2` is deprecated. This bumps it to `v4`.
=> Bump `cache` action

.github/workflows/update_report.sh
The CI refers to `GIT_REF` (which does not exist) instead of `GITHUB_REF`.
=> Fix reference to `GITHUB_REF`

.github/workflows/sv-tests-ci.yml
CI fails because one of the `sv-parser` dependencies expects newer `rustc` version (`1.81` according to the error message).
=> Bump rustc version for sv-parser

.github/workflows/sv-tests-ci.yml
Many jobs in `sv-tests-ci` emit `/bin/sh: 1: file: not found` error messages. Installing `file` solves the issue.
=> Fix `/bin/sh: 1: file: not found` errors

.github/workflows/comment-pr.yml, .github/workflows/sv-tests-ci.yml
Changes were made according to this [guide](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
=> Fix `save-output` deprecation warnings

generators/ivtest
Excluding `pr1520314` test from ivtests, since it doesn't compile with other simulators. The test is trying to assign signals that were previously associated with other signals, resulting in compilation errors.
=> Exclude a broken test from ivtests

.github/dependabot.yml
Remove dependabot config in the hope that restoring it later will fix it not opening new PRs.
=> Remove dependabot config

tools/runners/circt_verilog.py
Fix a typo in the circt-verilog Python runner script.
=> Fix parse-only mode for circt-verilog

.github/workflows/sv-tests-ci.yml, tools/runners.mk
Verible installation is [done differently](https://github.com/chipsalliance/verible/pull/2298) now, reflected by this change.
=> Bump Verible to `7aae5c08`

tests/chapter-13/13.3--task-label.sv, tests/chapter-13/13.4--function-label.sv, tests/chapter-23/23.2--module-label.sv
As per LRM 1800-2017, section 9.3.4, added task/function/module with named labels.
=> Add test for named function/task/module end- block

tools/runners/yosys_slang.py
Transfers more flags from the slang runner to yosys-slang to work around quirks of particular test cases. Add additional flags to make yosys-slang more lenient.
=> Update yosys-slang flags

conf/generators/meta-path/basejump.json
This test references an undefined macro:
```
../../../third_party/cores/basejump_stl/bsg_dmc/bsg_dmc_xilinx_ui_trace_replay.sv:22:36: error: unknown macro or compiler directive '`bsg_dmc_trace_entry_width'
localparam trace_data_width_lp = `bsg_dmc_trace_entry_width(data_width_p, addr_width_p)
^~~~~~~~~~~~~~~~~~~~~~~~~~
```
Probably this file is not meant to be used standalone but as part of some other parent module when used with basejump properly as a library.
=> Blacklist invalid test from basejump

generators/veer-config
It seems like the VeeR-EL2 build was never setup properly and so has always failed with all tools that do real compilation. This diff attempts to fix.
=> Fix VeeR-EL2 build

.github/workflows/comment-pr.yml
According to [the docs](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#multiline-strings). Hopefully it works.
=> Fix newline and other escaping in `comment-pr` CI workflow

.gitmodules, conf/lrm.conf, generators/ivtest
Reverts chipsalliance/sv-tests#7303 as that broke `ivtest` for all tools other than Icarus. I'll try the fix again, properly this time.
=> Revert "Update path to `ivtest`"

.github/workflows/sv-tests-ci.yml, .gitmodules, conf/lrm.conf, generators/ivtest
Another attempt at fixing #7297.
This time, always clones `icarus` in CI.
=> Fix `ivtest` path, always clone `icarus`

generators/ivtest
Blacklist some "new" IV tests that have appeared due to #7338, and test iv-specific versus SystemVerilog-universal stuff.
=> Add ivtest disables

conf/fusesoc-configs/ibex-sim.yml, conf/fusesoc-configs/ibex-synth.yml, conf/fusesoc-configs/veer-eh1-sim.yml, conf/fusesoc-configs/veer-eh1-synth.yml
Add circt-verilog as a compatible runner to the fusesoc config for the Ibex and VeeR cores.
=> Enable circt-verilog on Ibex and VeeR
